### ISSUE TITLE
Run goimports to help with missing imports in .vugu files

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#10]
See how feasible this is.  Could help make dev experience a bit smoother.  Might make sense to do as part of #9 (vugufmt)

**Comment by erinpentecost** [comment]
Since goimports formats code, this is a simple swap in vugufmt. I'll try it out.

**Comment by bradleypeabody** [comment]
I'm going to go ahead and close this.  Seems like vugufmt is a better place to be doing this anyway.  The vugu code generator now deduplicates imports which handles some of the problem.  And since vugufmt does goimports, I think we're set on this point.
