### ISSUE TITLE
How does one "read" from HTML to Go using Vugu?

### ISSUE THREAD

**Issue by serge-hulne** [vugu/vugu#100]
For instance, how does one read the text value of an <input> or <textarea> HTML tag from the poibt of view of Vugu?

**Comment by bradleypeabody** [comment]
You can set an event on `change` to fire when the value is updated.  E.g.

```
<textarea @change='c.SomeValue=event.PropString("target", "value")'></textarea>
```

Where `SomeValue` is a string field on your component struct.

NOTE: This is using the latest code from master, see: https://github.com/vugu/vugu/wiki/Refactor-Notes---Sep-2019

**Comment by serge-hulne** [comment]
Cool !

Thank you very much.

**Comment by Entrio** [comment]
Hi,
I am getting an error:

2020/01/13 15:40:04 Error from ParserGoPkg: error parsing "root.vugu": unable to parse DOM event handler expression "data.SomeValue=event.PropString(\"target\", \"value\")"

**Comment by itstmyi** [comment]
First please try this example :  vugu/wasm-test-suite/test-003-prop/root.vugu
Please pay attention to go.mod and change "require" section  as the following :
require (
	github.com/vugu/vugu master
)
Good luck .
