### ISSUE TITLE
Rendering a collection with vg-for shows the wrong number of elements when the size of the collection decreased after an update.

### ISSUE THREAD

**Issue by mazzegi** [vugu/vugu#101]
**Describe the bug**
Rendering a variable size collection with `vg-for` shows the wrong number of elements when the size of the collection decreased after an update. 

**Software Versions**
Vugu version: v0.1.1-0.20191230174203-fe17e20eb6ce
Go version: go1.13.4 linux/amd64
Browser and version: Chrome, Version 79.0.3945.117 (Official Build) (64-bit)

**To Reproduce**
The .vugu file below illustrates the issue:

```
<div>
    <button @click='c.Make(2, event)'>Make 2</button>
    <button @click='c.Make(6, event)'>Make 6</button>

    <div vg-for='_,n := range c.Numbers' vg-key='n' >            
        <div vg-html='n'></div>        
    </div>
</div>

<script type="application/x-go">
import(
    "fmt"
    "log"    

    "github.com/vugu/vugu"
)

type Root struct {       
    Numbers []string `vugu:"data"`
}

func (c *Root) Make(cnt int, event *vugu.DOMEvent) {
        event.PreventDefault()	
	go func() {        
		ee := event.EventEnv()
		ee.Lock()
		defer ee.UnlockRender()

               log.Printf("show %d", cnt)
		c.Numbers = make([]string, cnt)
		for i := 0; i < cnt; i++ {
			c.Numbers[i] = fmt.Sprintf("Number %d", i+1)
		}
	}()
}
</script>
```

When clicking "Make 2", two items are shown.
When clicking "Make 6", six items are shown.
When clicking "Make 2" again, five items are shown.

**Expected behavior**
When clicking "Make 2", two items are shown.
When clicking "Make 6", six items are shown.
When clicking "Make 2" again, two items are shown.

**Comment by bradleypeabody** [comment]
Thanks for reporting this.  I'm looking into it and will post any updates as soon as I have them.  Might be related to https://github.com/vugu/vugu/issues/99

**Comment by itstmyi** [comment]
Any new update about this issue ? Thanks .

**Comment by jyellick** [comment]
FWIW, I'm running into this as well.

**Comment by bradleypeabody** [comment]
@mazzegi @jyellick I just pushed a fix for this to master.  Can you please try again with the latest code?

**Comment by mazzegi** [comment]
Just gave it a quick try. At least the illustrating example works now.

**Comment by bradleypeabody** [comment]
Excellent.  I think we're good on this.
