### ISSUE TITLE
What's the status of this project now? any new roadmap planned?

### ISSUE THREAD

**Issue by giter** [vugu/vugu#103]
**Question**
...your question...

**Is your question related to a problem? Please describe.**

**Suggested Changes**
If applicable, please provide any suggestions of how to improve.

**Additional context**
Add any other context, info, files, etc. related to your question.

**Comment by bradleypeabody** [comment]
@giter Dev has been a bit thin lately but it will definitely pick up and hopefully soon.   I'm speaking about Vugu at GopherCon in June (https://www.gophercon.com/agenda/session/233435) so I plan to make a lot more progress and smooth things out as much as possible before then.

**Comment by itstmyi** [comment]
That's good news .
