### ISSUE TITLE
about vugufmt

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#106]
It seems vugufmt hasn't been updated for a long time .
My vugu file can run and work without any error . But If I check it by runing vugufmt , it can find many errors in my GO code part . Is there anything wrong with me ?
Errors are such as the following :
./root.vugu:89:1: expected statement, found 'import'
<standard input>:22:30: expected ';', found '{'
<standard input>:67:1: expected declaration, found ent

Thanks .

**Comment by bradleypeabody** [comment]
> Is there anything wrong with me ?

Nope, there is nothing wrong with you :) 

Yeah I haven't looked at this code in a long while. The main parser has been rewritten since that was done so it needs review and updating.  It would be great to fix but I think it's lower priority than addressing main features or updating the docs/site
