### ISSUE TITLE
Any difference between "func (c *Root) MyFunc()" and "func MyFunc (c *Root)" in Vugu ?

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#107]
I mean those functions which don't invoked directly by event handle . I think "c.MyFunc()" and "MyFunc(c)" do the same except that "c.MyFunc()" can be invoked as an event handle  .

Thanks for any information .

**Comment by bradleypeabody** [comment]
I think it's better practice to use `func (c *Root) MyFunc()` but I believe either way will work correctly.  I'm pretty sure you can call any function in an event handler with the latest code on master, even if it is not a method of the component (e.g. `func MyFunc (c *Root)`)
