### ISSUE TITLE
Failed to modify html element value by ":value"

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#111]
[root.vugu.txt](https://github.com/vugu/vugu/files/4368865/root.vugu.txt)

My source code file is above .
The text value of "Input" html element can be changed by  any of the two buttons  when the application runs at the first time .
But after I change the value by choosing one option (or changing its value by typing sth) of the "Input" html element , the text value of "Input" html element can't be changed again by  any of the two buttons .

Thanks for any information .

**Comment by bradleypeabody** [comment]
On the <input> tag try using .value instead of :value, e.g. `.value="c.testoptionvalue"`

Also, in order to detect changes make sure `testingoptionvalue` is exported, i.g. `Testingoptionvalue` and add the struct tag `vugu:"data"`.

See if those two edits resolve the issue.

**Comment by itstmyi** [comment]
good answer . thanks .
