### ISSUE TITLE
fail to set cookie  from web server when runing a vugu application

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#113]
I run a vugu file in "http://192.168.8.218:7944/" by "go run devserver.go" . 

In this application/file , I send a post request to the web server(Gin web framework on 192.168.8.X) then the web server  sets a cookie and responds with "http code OK200" to the  http client of vugu file .

I can get the right   "http code OK200"  response from  http client of vugu application , but no cookie is found  in the browser (Firefox or Chrome) .  

I guess I should deal with the http head cookie's  information manually in vugu file . Is this right ?

Thanks for any advice .

**Comment by itstmyi** [comment]
I made a mistake .

Run "go run dist.go" to produce 3 staic files (index.html/wasm_exec.js/main.wasm) , deploy them to a static folder of the web server and access "index.html" of the web server by a browser which can support runing wasm file .

That's it . Sorry for disturbing .

**Comment by bradleypeabody** [comment]
No worries, glad it worked out.
