### ISSUE TITLE
How to pop up a new window of the browser(or a new tab page of it)  from Vugu application ? 

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#114]
One way is writing a dynamic <a> element as a hyper-link , so that it can be clicked manually by the operator . Could this action be taken by some automatic code ? (I also want to pass some parameters to the new page from current vugu application page .)

Thanks for any advice .

**Comment by bradleypeabody** [comment]
The same mechanism that normally exist for web pages should apply in a Vugu app.   Options would include a regular `<a href="..." target="_blank">` link or using `window.open` (https://developer.mozilla.org/en-US/docs/Web/API/Window/open), which you can call through the `js` package with something like `js.Global().Get("window").Call("open", ...)`
