### ISSUE TITLE
issue after updating from vugu@v0.0.0-20200322002911-7d3a6c0162c2 to any new version

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#116]
It happened when I updated to all the new versions including the latest v0.2.0  from vugu@v0.0.0-20200322002911-7d3a6c0162c2 .

My vugu code  is very simple , the error is like following :
github.com/vugu/vugu/js
..\..\..\..\..\..\..\pkg\mod\github.com\vugu\vugu@v0.2.0\js\impl-js.go:227:21: js.Value(v).IsUndefined undefined (type js.Value has no field or method IsUndefined)
..\..\..\..\..\..\..\pkg\mod\github.com\vugu\vugu@v0.2.0\js\impl-js.go:231:21: js.Value(v).IsNull undefined (type js.Value has no field or method IsNull)

Thanks for any information .

**Comment by bradleypeabody** [comment]
Please try updating to Go 1.14.x, I believe IsNull and IsUndefined were recently introduced.

**Comment by itstmyi** [comment]
Thanks .

**Comment by bradleypeabody** [comment]
Great, glad it's working for you!
