### ISSUE TITLE
There should be a way to properly handle `disabled` and other HTML attributes that have no value and/or need to be conditionally output

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#121]
**Is your feature request related to a problem? Please describe.**

There is currently no way to express the following markup with a condition for the `disabled` attribute to be shown or hidden based on a Go expression:

```html
<div><button disabled>test</button></div>
```

This is because the only option for dynamic attributes is the `:` syntax but this always outputs the attribute.

**Describe the solution you'd like**

This is still open for discussion but the current idea being considered is to essentially allow the colon syntax with e.g. `:disabled="...` to hide attributes where the Go value evaluates to `false` or `nil` based on type, more specifically:

- `string` - value is used directly as attr value
- `[any number type]` - converted to a string using applicable `strconv` func
- `bool` - if false does not output attribute, if true outputs it with no value.
- `[pointers to these types]` - will be followed and the value used, if nil then the attribute hidden as if it were `false`
- (see explanation below about `VGAttributeList() []VGAttribute`)
- `String()` - if it implements `String() string` then we call that method and use it as if it were a `string`
- anything else is undefined behavior but currently implemented with fmt.Sprint

We should also consider if there are one or more interfaces here that could provide a good way for arbitrary types to express how they want to be translated to an attribute.  E.g. `type VGAttributeLister interface { VGAttributeList() []VGAttribute }` - we could check if a type implements that interface and use it for attribute conversion in that case.  This should take precedence over the String() method if the type has both.  Interestingly, this also means there could potentially be a `VGAttributeListerFunc` type which (following the pattern of `http.HandlerFunc`) makes it easy to write custom code that emits whatever attributes it wants.  It's a bit unclear what the attribute name means on these VGAttribute structs returned - since there is already a name specified in the `:disabled="...` part.  Possibly returning `VGAttribute{Val:"whatever"}` with an empty attr name would get the name `disabled` from the attr in the source, whereas if you specify an attr name in the return it is used.  This is TBD, but overall this could be really useful and be both convenient for simple cases but also handle complex ones well.

Once implemented https://www.vugu.org/doc/files/markup should be updated.  For the idea of providing extra attributes we should give in the doc an example an possibly a convention, e.g. an example showing `<div :extra-attr="vugu.VGAttributeListerFunc(func() ...)"` - showing how the function is implemented as well as using `extra-attr` - since the attribute name is here is ignored they could call it anything but I think it's a good idea to give a best practice in the doc.  There is no benefit to people doing it inconsistently.

**Describe alternatives you've considered**

Other options discussed include introducing a syntax like `?disabled` or providing a method like `vugu.EmptyAttrIf(bool)` that could return some special value to indicate the attribute should be hidden.  The solution noted above provides all the functionality for either of these approaches and does not introduce new syntax, instead it simply clarifies and adds more functionality to the existing syntax.

**Additional context**

This arises with `disabled`, `checked`, `selected` and other such attributes.  

There may also be a similar change done for `<pkg:Comp>` references, but it is unclear how that will work or how much overlap there is.  This issue can most likely be resolved and handle HTML attributes like `disabled`, etc. without having to figure out if there is something similar for component references.

**Comment by tbe** [comment]
I like the Idea of the `VGAttributeLister`. I would propose the following rules for the usage of the interface:

- This interface may only be used if the attribute name is `_` or `data`
- If the name is `_`, the attribute names are taken from the returned Attribute list
- If the name is `data`, for each attribute returned, we create an attribute `data-$name`

_For the reasons why:_
- I can not imagine any usecase where we set a single attribute and use a `AttributeLister` interface for this. Using a `fmt.Stringer()` is more convenient in this case.
- `data-*` attributes are HTML5 spec elements, it makes sense to provide a simple way to set these
- `_` does not occur on the wild (i hope so) and makes the special case pretty clear i hope. ( on the other hand, it collides with golangs `_`, my be confusing)

**Comment by bradleypeabody** [comment]
I think limiting the name of the attribute when using VGAttributeLister is an excellent idea.

I'm not in favor of the magic involved with prefixing `data-` to the names, I feel like this is simple enough that the developer should just do it, or we can provide a convenience function.

**Comment by bradleypeabody** [comment]
Per discussion on Slack, the plan is `AttributeLister` interface can only be used with `:` as the attribute name, i.e. `:="someAttrLister"` and the code generator will emit code that checks the type.  If you do `:a="someAttrLister"` the other rules apply and it will be unaware that the AttributeLister interface is implemented.

So far we're going to leave off any special handling for `data` and delay that decision until we have some use cases to work with.

**Comment by tbe** [comment]
Another thing: Should we implement a function type `type AttributeList() []VGAttribute`? This may come handy, for example if there is a component composed of a many nodes, like a complex form, and we need attributes per node. For example for something like form validation.

The `VGAttributeLister` interface itself is very useful for components where only one node requires attributes.

**Comment by bradleypeabody** [comment]
This is merged now, plus vg-attr= works like :=.

Just need to update the doc and release.

**Comment by bradleypeabody** [comment]
All done now and documented here https://www.vugu.org/doc/files/markup

Will be released later tomorrow/today.
