### ISSUE TITLE
vugugen should have a good technique for emitting certain missing types and methods (needed for component events)

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#128]
**Is your feature request related to a problem? Please describe.**
There is a growing list of things that must exist in order for certain functionality to work and the code generator should have a good "just make one if it doesn't exist" behavior.

This already exists for emitting a `type Component struct {}` in the case that the developer has not already declared such a struct.  I believe this behavior is a good thing and allows a balance where developers can rapidly get started without having to understand all of the bits involved with a Vugu program (and without having to type a bunch of boilerplate code), but then when they need to customize they can just add the appropriate type themselves and it's existence automatically takes over from the code generator.

**Describe the solution you'd like**
I'm considering adding a comment format like so:
```
//vugugen:event Something
```

This declares that an event (a "component event", not a "dom event") named Something should exist, which implies a `type SomethingEvent struct`, `type SomethingHandler interface` and `type SomethingHandlerFunc func` and `func (f SomethingHandlerFunc) SomethingHandle(SomethingEvent)`.

There is an exact pattern here and the code generator can easily scan the package and determine if these things already exist and emit them if not.  As mentioned above, some similar functionality already exists to emit the type struct for a component type if it's missing.  With this update, the mechanism would become more formalized and extend it to emit the things needed for component events.  It also provide a pattern where if other similar functionality is needed it can use this `//vugugen:whatever` comment format for new situations as they arise.

**Describe alternatives you've considered**
For events I've considered just making all of the handlers functions, so rather than bothering with SomethingHandler and SomeHandlerFunc (in addition to SomethingEvent which has the actual event data), there would just be SomethingEvent and a handler for it is `func(SomethingEvent)`.  This is definitely simpler, but it is also less powerful and does not utilize the Go type system particularly well.  The biggest advantage of this approach is that it's simpler for the developer to get started with.  However if the SomethingHandler and SomethingHandlerFunc can be easily generated by vugugen where missing, it seems like it would be better to "do it right" and use SomethingHandler and SomethingHandlerFunc (thus allowing any type that implements the SomethingHandler interface to receive that event).

**Additional context**
While it seems possible that this could be over-used and we end up with way too much extra code being generated, I don't think that's the situation right now and this can be avoided with careful planning.  The situation we have right now is that in order for `<pkg:Comp @Something=...` to work properly, a few different types related to "Something" must exist, and making developers carefully type this out for even the simplest of cases when it can be automatically generated seems like a significant hassle.  So I think the idea is sound, but each //vugugen: thing added needs careful planning to decide if it's really something that we want to handle with codegen as opposed to dealing with it some other way.

**Comment by bradleypeabody** [comment]
Implemented here https://github.com/vugu/vugu/blob/vgform-wip/gen/missing-fixer.go

Work's pretty much as described, names are slightly different.

**Comment by owenwaller** [comment]
Closing as this seems to exist already.
