### ISSUE TITLE
Range Over Data Stream

### ISSUE THREAD

**Issue by charles-d-burton** [vugu/vugu#129]
**Question**
Not sure if it's possible, but I'm curious to know if it's possible to dynamically update a component base on a data stream such as Server Sent Events or Websockets.  Currently I'm trying to do this, but it doesn't seem possible to range over a chan in vugu. The first question I suppose is how to get it to start the datastream on page load, meaning it'll connect to the backend stream and start populating the chan.  Then how do I range over a channel and keep the UI up to date with the latest values from the stream.

```
<div class="mt-5">
            <h1>Data Stream Here</h1>
            <p vg-for='item := range c.Stream.Data'>
                <div vg-html="item"></div>
             </p>
        </div>
```

```go
import "time"

type Root struct {
    ShowWasm bool `vugu:"data"`
    ShowGo bool   `vugu:"data"`
    ShowVugu bool `vugu:"data"`
    Stream stream `vugu:"data"`
}

type stream struct {
    Data chan string
}
```

**Comment by bradleypeabody** [comment]
This should be do-able.  Have a look here https://github.com/vugu/vugu/blob/master/wasm-test-suite/test-011-wire/setup.go for an example of making a vuguSetup function which has access to the [EventEnv](https://godoc.org/github.com/vugu/vugu#EventEnv).  You can make your HTTP request in a goroutine from this function if you want it to happen on page load (if not then you can also capture the relevant DOM event and fire it off there too - either way should work).

Once you have an EventEnv you Lock(), make your change, and then UnlockRender() to tell it to update the page.  There is a bit more information as well on using EventEnv in the [DOM Events](https://www.vugu.org/doc/dom-events) section of the site.

**Comment by charles-d-burton** [comment]
Awesome, thank you.  That got me on the right track.  I still can't get get it to range over a chan, but updating the data element seems to work for what I need.
