### ISSUE TITLE
Streamline installation on Ubuntu / "permission denied"

### ISSUE THREAD

**Issue by hubyhuby** [vugu/vugu#134]
**Is your feature request related to a problem? Please describe.**
When following the quick start guide on Ubuntu this doesn t work out of the box.
https://www.vugu.org/doc/start
The first command gives you right errors "permission denied", I tried with Sudo aswell with no luck.
go get -u github.com/vugu/vgrun

Finally I had to copy past the two projects "vgrun" and "vugugen"
Manually from mod to another folder, compile it and copy the bins to $GOBIN

Now I can generate and run a project.

This is the type of error I get :

/vgrun -install-tools
2020/05/03 20:03:51 Installing vugugen
2020/05/03 20:03:52 Error installing vugugen: exit status 1; full output:
go: found github.com/vugu/vugu/cmd/vugugen in github.com/vugu/vugu v0.3.0
go get github.com/vug u/vugu/cmd/vugugen: copying /tmp/go-build671629333/b001/exe/a.out: open /usr/lib/go/bin/vugugen: permission denied

**Describe the solution you'd like**
I'd like a more streamline experience for users of Ubuntu distributions.
Maybe the solution is to modify your script to copy the binaries in $GOBIN.

**Additional context**
Ubuntu mate 18.04 
go version go1.14.2 linux/amd64

export GOPATH=/home/ME/Dropbox/go
export GOROOT=/usr/lib/go/
export PROJBIN=/home/ME/Dropbox/go/bin/
export GOBIN=/usr/lib/go/bin
export PATH=$PATH:$GOBIN:$PROJBIN
export GO111MODULE=on

**Comment by bradleypeabody** [comment]
Definitely strange.  If you do `go get -u -x -v github.com/vugu/vugu/cmd/vugugen` does this produce the same error?  If so please send me the full output.  The code that is failing is here: https://github.com/vugu/vgrun/blob/master/vgrun-main.go#L39 and it should be just running the command above (I added the -x -v to give more detailed output).

**Comment by hubyhuby** [comment]
Dear @bradleypeabody ,
Thanks for your quick answer.
I think I have a problem with my GOBIN I modified since upgrading lately to 1.14 to run this project.
Don't bother with this issue; I will try to fix it on my machine and close this feature.

**Comment by hubyhuby** [comment]
Closing :

It was a misconfiguration, this is working perfectly nice on Ubuntu.
I just reinstalled completely Go and set now my profile s path to only (default go installation) :  
export GOBIN=/home/ME/go/bin
export PATH=$PATH:$GOBIN


Thanks @bradleypeabody for this wonderfull project.
Looking forward for the 1.0 ;)
Hope one day Wasm will have garbage collection features, so the distributed Go-wasm will be ~300Kb rather than 3 000 kb today ( ~1Mo gziped for the current vugu exemple)

**Comment by bradleypeabody** [comment]
FYI support for building with Tinygo is in-progress - this will address the binary size issue.  I have a simple example that properly renders a page with 198k :)   With some luck, Vugu will officially support Tinygo compilation in the coming weeks, we'll see.
