### ISSUE TITLE
Error installing vugugen

### ISSUE THREAD

**Issue by ijt** [vugu/vugu#140]
**Describe the bug**
Running `vgrun -install-tools` reports "Error installing vugugen: ... working directory is not part of a module".

**Software Versions**
Vugu version: ?
Go version: 1.14 darwin/amd64
Browser and version: n/a

**To Reproduce**
```
go get -u github.com/vugu/vgrun
vgrun -install-tools
```

**Expected behavior**
I expected the command to run successfully.

**Additional Notes**
Instead it gave this output:

```
2020/06/10 16:34:20 Installing vugugen
2020/06/10 16:34:21 Error installing vugugen: exit status 1; full output:
can't load package: cannot find module providing package github.com/vugu/vugu/cmd/vugugen: working directory is not part of a module
```

I was able to work around it by doing this:
```
cd /tmp
mkdir foo
cd foo
go mod init github.com/ijt/foo
vgrun -install-tools
```
That ran successfully.

**Comment by bradleypeabody** [comment]
Interesting.  I get different results when I try this (Go 1.14.3 on Mac).  From a directory with no go.mod in it:

```
$ go get -u github.com/vugu/vgrun
$ vgrun -install-tools
2020/06/11 11:52:39 Installing vugugen
2020/06/11 11:52:43 Installing vgrgen
$
```

Is there anything else significant about the directory you were in when you ran `vgrun -install-tools` ?  If you can provide the `go env` output from that folder where it gave the error, possibly that would give us a clue.

**Comment by ijt** [comment]
I don't know, lost context from when I filed the issue.

Here's what happens when I run it in a new directory:
```sh
[ /tmp ] cd $(mktemp -d)
[ /var/folders/fy/xkp_5b8n54d2x3826xsfwhhr0000gn/T/tmp.KB6JJFAX ] vgrun -install-tools
2020/06/19 17:15:30 Installing vugugen
2020/06/19 17:15:30 Error installing vugugen: exit status 1; full output:
can't load package: cannot find module providing package github.com/vugu/vugu/cmd/vugugen: working directory is not part of a module

[ /var/folders/fy/xkp_5b8n54d2x3826xsfwhhr0000gn/T/tmp.KB6JJFAX ] go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/issactrotts/Library/Caches/go-build"
GOENV="/Users/issactrotts/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/issactrotts"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fy/xkp_5b8n54d2x3826xsfwhhr0000gn/T/go-build210582231=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bradleypeabody** [comment]
Thanks, I see the issue. GO111MODULE is set to "on".  I'm able to reproduce by toggling GO111MODULE from being unset vs "on" and it causes the error to not happen/happen.

Can you please re-test with GO111MODULE unset?  For example:

```
GO111MODULE="" vgrun -install-tools
```

Did you change the value of GO111MODULE on your system or is this default? (It looks like you're using Homebrew's Go, perhaps it has different defaults?)

**Comment by ijt** [comment]
Hi Brad, that did the trick. I changed the value on my system. I'm thinking
maybe it wasn't the best choice.

**Comment by bradleypeabody** [comment]
No worries, at we got to the bottom of the mystery 👍
