### ISSUE TITLE
How do you recomment to inject an event into the Vugu render cycle?

### ISSUE THREAD

**Issue by ebudan** [vugu/vugu#145]
**How do you recomment to inject an event into the Vugu render cycle?**

Background: I'm looking at ways to eliminate javascript completely from a simple(-ish) GUI working with websocket events against a stateful back-end. Vugu largely fits the bill, but I'm slighty skittish about some details. 

Is it safe to grab a reference to the EventEnv in vuguSetup() in order to later trigger re-rendering after modifying components in another thread (or goroutine)?

I have defined a vuguSetup() that creates a controller with a websocket client and a reference to the vuguSetup() vugu.EventEnv, and I use that to Lock() and UnlockRender() when relaying incoming messages to their designated recipient components. The fact that vugu is diligently providing DOMEvent.EventEnv() makes me suspect I may be asking for problems.

**Comment by bradleypeabody** [comment]
> Is it safe to grab a reference to the EventEnv in vuguSetup()
Yes, this is safe and is one of the intended uses.

There is no inherent issue with triggering re-renders from another goroutine.  Obviously if this is done excessively you can get a situation where too much time is spent updating the UI (as with any reactive-type UI library/framework).  But based on your description the idea of receiving data from a websocket and then using EventEnv to lock and update data and then trigger a re-render based on that new data - that is exactly the intended use case.  I don't see any inherent problem.

**Comment by owenwaller** [comment]
This seems to be answered, so closing.
