### ISSUE TITLE
Where is the contibution guide

### ISSUE THREAD

**Issue by alwindoss** [vugu/vugu#148]
**Question**
I tried looking in the repository and in the website, I did not see a link to contribution guide. Is there a contribution guide?

**Is your question related to a problem? Please describe.**
For a person who is interested in contributing to this project there should be a guide that helps him get started with vugu code base

**Suggested Changes**
A `Contributing.md` file in the root of the project and also a page on the website dedicated to how a new person can start contributing whether it is with Docs or with Code

**Comment by bradleypeabody** [comment]
Excellent point.  I'll look around and see what is common practice for this and put something together.  Any suggestions of what would be a good starting point are welcome.

**Comment by alwindoss** [comment]
Some things that would ease a developer into contributing could be:

> Project structure or layout so he can get around the code base and understand it

> Location of different parts of the library and what they do

As a person who wants to contribute to documentation
> Where can the documentation go

> How to see the documentation changes once done

We could start with this and the refine it to include other common questions we encounter along the way.

**Comment by bradleypeabody** [comment]
@alwindoss Great and thanks.  I put something together for this - https://github.com/vugu/vugu/pull/149 . Please Let me know any feedback.

**Comment by alwindoss** [comment]
I have given some minor feedback on the text.

**Comment by bradleypeabody** [comment]
Thanks for your help on this.  Now we have a CONTRIBUTING.md :)

https://github.com/vugu/vugu/blob/master/CONTRIBUTING.md

**Comment by alwindoss** [comment]
@bradleypeabody in the "Enforcement" section the email needs to be updated. Currently it says "[INSERT EMAIL ADDRESS]"

**Comment by bradleypeabody** [comment]
@alwindoss Good catch, fixed.
