### ISSUE TITLE
TailwindCSS integration

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#150]
I'm considering doing some work to make TailwindCSS integrate well with Vugu.

Let's see where this discussion goes https://github.com/tailwindlabs/tailwindcss/discussions/2126 and then take it from there.

Related: https://github.com/vugu/vugu/issues/146

**Comment by zyhong** [comment]
TailwindCSS should be very nice. Very configurable and we will not have the situation that most user have the same "face" like bootstrap. Not sure if you are aware but maybe project could give some inspiration:
 https://github.com/matyunya/smelte

**Comment by bradleypeabody** [comment]
Work in progress: https://github.com/gotailwindcss/tailwind
