### ISSUE TITLE
Tinygo wasm error using example

### ISSUE THREAD

**Issue by DamianImrich** [vugu/vugu#151]
**Describe the bug**
I am trying vugu-examples/tinygo using docker (with no changes to example). Everything works well until browser instantiate wasm file and throws error
`Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #14 module="env" function="syscall.Exit" error: function import requires a callable`

**Software Versions**
Vugu version: v0.3.2
Go version: locally 1.14.4 (vugu/tinygo-dev docker image)
TinyGo version: from vugu/tinygo-dev docker image
Browser and version: Chrome 84

**To Reproduce**
`go run devserver.go` and open http://localhost:8844/

**Expected behavior**
Wasm gets loaded and vugu renders components

**Comment by bradleypeabody** [comment]
Interesting.  I haven't been able to reproduce.

- Which OS is this on?
- Just to confirm - this error appears immediately once the wasm stuff is initialized on the page? (As opposed to after user interaction.)
- If there's a way to send a screen shot with the console panel open that might help give some more info about what is happening.
