### ISSUE TITLE
Run code before a component renders

### ISSUE THREAD

**Issue by jprukner** [vugu/vugu#157]
**Question**
How do I run code before a component is rendered?

**Additional context**
Example: There is a vugu-based site example.com/secret. When visited by unauthenticated user, I would like to call c.Navigate("/", url.Values{}). I don't know where I should put it so it gets executed before the site gets rendered.
Right now, an empty site gets rendered because a backend service prevents unauthenticated user from loading the secret.

**Comment by jprukner** [comment]
As workaround I use <span hidden vg-content='c.list()'></span>.

where CheckUser checks if user is authenticated and does redirection if user is not authenticated.

**Comment by jprukner** [comment]
I haven't figured out how to request rerendering for the "workaround". Any idea?

Proper solution would be to react to some kind of event, I haven't figured out what event it should be...

**Comment by bradleypeabody** [comment]
Hm, can you give me an example of how you would approach this problem with a different framework?  Perhaps that will lead to a correlation with Vugu.  My first question is I'm not sure if this check to see if the user is logged in is something that requires a network request or if that data is available immediately in the application.

If it is available immediately, then it sounds like this might need to be accommodated for in vgrouter - not entirely unlike how backend code will perform authentication and then redirect using a 302 to the appropriate resource. (Obviously there are differences, but they both share the idea that code which handles that route provides access control and sends the user elsewhere if not allowed).

**Comment by jprukner** [comment]
Thanks for the response @bradleypeabody!

Let's forget about authentication for now. You are correct, I don't have to access network resource to check if user is logged in.

Imagine I click on a button at /somePage. This will redirect me to /someOtherPage, where I want to fetch and display data. But I'd like the fetching to be asynchronous.

Well, I am not a frontend specialist, I am sorry if this is nonsensical issue. 
I tried angular once. The way I'd do it in angular,  I think, would be to fetch the data and pass it to the component on its creation. In Vugu, this would mean to fetch data in vgrouter. I tried it, it works.

How do I do it asynchronously? 

setup.go
```go
// ...
	router.MustAddRouteExact("/someOtherPage",
		vgrouter.RouteHandlerFunc(func(rm *vgrouter.RouteMatch) {

			if !creds.IsSet() {
				router.Navigate("/", url.Values{})
				return
			}
			c := &SomeOtherPage{}
			root.Body = c  
			go func(){
				c.Fetch()
				// TODO REQUEST RE-RENDER TO REPLACE PLACE HOLDERS
				// WHEN FETCHING IS DONE.
			}()
		}))
// ...
```

**Comment by bradleypeabody** [comment]
Hm, interesting.  The way I would approach this problem of fetching data upon viewing a page would be to instead use BeforeBuild() (see https://www.vugu.org/doc/components#vg-comp) on SomeOtherPage.  Example:

some-other-page.vugu
```
<script type="application/x-go">
type SomeOtherPage struct {
    inited bool
    WhateverData string `vugu:"data"`
}
func (c *SomeOtherPage)BeforeBuild() {
    if !c.inited {
        c.inited = true
        go func() {
            res, err := http.Get(...)
            c.WhateverData = ... // FIXME: need EventEnv to be able to trigger re-render
        }()
    }
}
</script>
```

Bummer... Yeah BeforeBuild doesn't have a way to tell Vugu to refresh when the data comes back.  I'm updating this issue https://github.com/vugu/vugu/issues/159 now - this is a great example of something that needs attention with these lifecycle events.

**Comment by jprukner** [comment]
@bradleypeabody Thanks for the BeforeBuild link, I missed that. It seems to work better than fetching data in vgrouter. I encountered a weird bug when fetching data in vgrouter. At the server side, request went fine but the goroutine that handled fetching stayed blocked in browser during handling second redirect (Navigate call). The fetching function was the same. I did not investigate it as it started to work when I removed my call to c.Fetch in vgrouter and renamed the Fetch method to BeforeBuild in SomeOtherPage component. It may have something to do with the fact I tunnel GRPC over websocket and thus some wierd combo may happened.

**Comment by bradleypeabody** [comment]
Ok cool.  Yeah BeforeBuild() is probably the right approach here.

Keep an eye out for better support soon as the issue mentioned above gets resolved.

On the deadlock stuff, if you run into something specific that is still hanging you up please post the code and I can have a look.

**Comment by jprukner** [comment]
> 
> Keep an eye out for better support soon as the issue mentioned above gets resolved.
> 
> On the deadlock stuff, if you run into something specific that is still hanging you up please post the code and I can have a look.

I will, thanks a lot. Closing the issue.
