### ISSUE TITLE
Lifecycle Events Proposal

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#159]
Various people and in various issues, including https://github.com/vugu/vugu/issues/26 https://github.com/vugu/vugu/issues/155 and https://github.com/vugu/vugu/issues/158 have pointed out that we need a workable set of "lifecycle events" that provide hooks to be called at certain times for each component in order to handle things like initialization, first render, etc.  We have BeforeBuild right now but more are needed, plus we need documentation that describes when to use what. This is an attempt at a proposal for that.

In sequence the way this would go is:

* A component is either created newly (First=true) or re-used from the prior build/render pass.

* `func (c *Comp)BeforeBuild(x vugu.BeforeBuildCtx)` - **called before a component's Build method, i.e. before the "virtual DOM" is computed** - the context would provide a `First() bool` to indicate if this is the first build. (the existing BeforeBuild() with no args would still be supported for now, possibly remove before 1.0)

* Build() method gets called

* TODO: I was tempted to put a lifecycle method here but I do not see how it could be of any use.  Maybe some sort of BeforeRender(), but without a use case to know what one would need to have access to, I feel like it's safer to just leave it off until we know what's needed.

* Rendering happens, synchronizing build output with browser DOM.

* `func (c *Comp)AfterRender(x vugu.AfterRenderCtx)` - **called after render occurs and virtual DOM is fully synced with browser DOM and layout has occurred** likewise this would have `First() bool` on the context to indicate first render.

The reason separate contexts are provided for these are so functionality can be added to them without breaking implementations.  Doing something like `AfterRender(firstTime bool)` is tempting for it's clarity but it's not good for maintenance and will probably lead to a proliferation of more lifecycle events to handle cases that could otherwise be handled by adding a method to vugu.AfterRenderCtx to just provide additional data to an existing lifecycle method.  Too many different lifecycle events presents its own problem and can lead to developer confusion about when to use which.

EDIT:
* I guess it might be easier to understand if instead of expecting people to implement BeforeBuild and check for First(), there could be an explicit `Init()` method.  And making it able to check for two interfaces one with just `Init()` and the other as `Init(x vugu.InitCtx)` - that would make it so the simple case of developer's just doing: `func (c *Comp)Init { ... ` would Just Work as expected (and maybe this option of with or without context should just be the standard for all such events).  There seems to be merit in this idea.
* We need to explicitly state where the "WireFunc" stuff goes (see https://www.vugu.org/doc/wiring) in this sequence. Probably it's fine for the wiring injection stuff to happen before Init() (probably better actually), but it definitely needs to be documented and made clear.  I'm not sure if there is a case for yet another lifecycle method that occurs before wiring is done, but again, without a use case, it's hard to justify.

**Comment by bradleypeabody** [comment]
To boil it down more and refine. Each event has a corresponding context, but its use is optional.  Sequence is:

* **Component created or reused** from last render.
* **Component passed to wire func** and is injected/wired, see https://godoc.org/github.com/vugu/vugu#BuildEnv.SetWireFunc
* Component **`Init()`** method called if component created newly/not reused
* Component **`BeforeBuild()`** method called
* Build() is called (note that Build is a generated method, so most developers won't do anything with this)
* NOTE: There is no AfterBuild() or BeforeRender() for now until someone can give an example of why it's needed
* **Rendering occurs**
* Component **`InitRender()`** method called if component created newly/not reused
* Component **`AfterRender()`** method called

**Comment by san-321** [comment]
It would also be nice to have a Destroy() method.
It could have been called after Build() for unused components from the previous build pass.
It would be useful for components that need to add event listeners to document or window to remove them when the component disappears

**Comment by bradleypeabody** [comment]
@san-321 I agree.  Adding it to the list above. I'm not sure what will be required to implement but it definitely seems useful enough to have as a requirement.

**Comment by bradleypeabody** [comment]
Refining the names a bit, I'm thinking the following might be more intuitive.  Infinitive verbs indicate a call that happens before something, past tense indicates after (Rendered).

* **Init()** - simple, obvious, commonly used
* **Compute()** - (instead of calling it BeforeBuild) this is shorter and more concise
* **Rendered()** - past tense avoids the need for "After", I'm not sure if a special case for "first rendered" is needed, could be implemented with `Rendered(ctx vugu.RenderedCtx) { if ctx.First() { ...` - depends on how common such a case is - compared to Init(), Rendered() should be used much less frequently (only for manual DOM manipulation)
* **Destroy()** - similar to the idea of a C++ "destructor", not sure if that's a good thing or a bad thing o.O

I like how short and to the point these are.

**Comment by bradleypeabody** [comment]
This is now implemented.  Documentation is at: https://www.vugu.org/doc/components#lifecycle

I'll go ahead and close this.  If there is feedback or further adjustments needed that can become a separate issue.
