### ISSUE TITLE
How to get event on @click?

### ISSUE THREAD

**Issue by Nv7-GitHub** [vugu/vugu#165]
**Question**
is there a way of getting the event js.Value on @click and other functions?

**Suggested Changes**
If not, could that be a feature?

**Additional context**
I want to get the target of the click function.

**Comment by bradleypeabody** [comment]
I think you're looking for JSEvent() on [DOMEvent](https://godoc.org/github.com/vugu/vugu#DOMEvent).  `JSEventTarget()` and `JSEventCurrentTarget()` are also available and probably will give you want you want.

**Comment by Nv7-GitHub** [comment]
How would you get this DOMEvent from inside an onclick function?

**Comment by bradleypeabody** [comment]
The relevant documentation is here: https://www.vugu.org/doc/dom-events

> The special variable `event` (of type vugu.DOMEvent) corresponds to the event data sent to us by the browser. It also provides some useful functionality such as a PreventDefault() method which corresponds to preventDefault

**Comment by Nv7-GitHub** [comment]
How did I not notice that? Thanks!
