### ISSUE TITLE
Is there a way to force Vugu to render?

### ISSUE THREAD

**Issue by Nv7-GitHub** [vugu/vugu#167]
**Question**
I have changed some variables through pointers and Vugu isn't re-rendering the HTML based on the changes. I have marked it as `vugu:"data"`. Is there a way to force Vugu to look for changes?

**Comment by Nv7-GitHub** [comment]
Most of the time it doesn't work, but sometimes it does. When it doesn't work, lots of things stop working.

**Comment by bradleypeabody** [comment]
Any DOM event being handled (e.g. with `@click=`) will trigger re-render.  However if you do something like fetching data from a server in a goroutine, you'll need to use EventEnv.Lock(); EventEnv.UnlockRender() to tell Vugu that you've made changes that require a re-render.  This is described a bit here: https://www.vugu.org/doc/dom-events

If rendering is stopping completely I would suspect something is panicing. Be sure to check your browser console to see if this is the case and if so where/why.

**Comment by Nv7-GitHub** [comment]
How do I use EventEnv? Is there any example code? I have struct Root, how do I lock it and render it?
