### ISSUE TITLE
Global event listener

### ISSUE THREAD

**Issue by HubertBL47** [vugu/vugu#169]
I apologize in advance for my bad english.

**Question**
Is there a way to have access to global event listener ?

**Description**
I am currently working on web App where i need to implement undo (ctr+z) and redo (ctr+y) features. Is there anything in vugu that can be used to listen for that kind of "keydown event" on global scale? In Javascript, i would have done something like this :
```
document.addEventListener("keydown", function(){
    ...
})
```
I have tried to add @keydown on my top div element, however the event does not seem to propagate every time to this top element.

Thank you.

**Comment by bradleypeabody** [comment]
There is nothing built into Vugu for this but you can use the `js` package to accomplish what you're after (see https://godoc.org/github.com/vugu/vugu/js and https://golang.org/pkg/syscall/js/ ).  e.g. `js.Global().Get("document").Call("addEventListener", ...`

**Comment by HubertBL47** [comment]
It worked, Thank you !

For anyone with the same issue, I did 

```
f := js.FuncOf(handleKey)
js.Global().Get("document").Call("addEventListener", "keydown", f)
```
I also had to add the eventEnv to lock and request rerender during ```handlekey()```
