### ISSUE TITLE
How to make a loader show up with a CPU-intensive task?

### ISSUE THREAD

**Issue by Nv7-GitHub** [vugu/vugu#170]
**Question**
I have a process that is called that has lots of loops and other slow things. I am using vugu's EventEnv to do Lock() and UnlockRender(). This does not show the loading image, even though this is running concurrently. I was able to get it to show up using `time.Sleep(time.Second)`, but this just added a second to a task that doesn't even take a second. When i tried it with `time.Sleep(time.Millisecond`, it stopped working again. I suspect this is because of the same reason that if you change the Document while in a forever loop in javascript, the document won't update until the loop is finished, which can make the document freeze.

**Comment by bradleypeabody** [comment]
If you're not already, you'll want to spin off your processing into a separate goroutine.   Although Go+wasm doesn't yet support running goroutines concurrently, it does have some form of scheduling that occurs which allows multiple goroutines to be executed in parallel.

Try breaking out your processing into a separate goroutine and if still issues please include the code in followup post and I can have a look.

**Comment by Nv7-GitHub** [comment]
You can find the code [here](https://github.com/Nv7-Github/nv7haven.tk), but more specifically in [this file](https://github.com/Nv7-GitHub/nv7haven.tk/blob/master/hella.vugu). It is already in a separate goroutine. I was able to fix it by doing `time.Sleep(time.Millisecond*15)` but it still feels like it is kind of hacky and not optimal.

**Comment by bradleypeabody** [comment]
Interesting.  Try moving the `c.Loading = true` into the @click handler, so e.g. `@click="c.Loading=true; go c.Calculate(event.EventEnv())"` and then you can remove the first four lines of `Calculate` and only Lock/UnlockRender at the end.  See if that works any better.

I suspect that the scheduling mechanism provided by the Go wasm runtime has trouble dealing with the specific structure you have there.

**Comment by Nv7-GitHub** [comment]
I did try that, it did not work. However I have now switched it to server-side, both because this seemed hacky and it reduced my binary by >5MB. Thanks for your help, maybe this issue will be fixed as WebAssembly with Go becomes more mature.
