### ISSUE TITLE
Get page to update from handler

### ISSUE THREAD

**Issue by Nv7-GitHub** [vugu/vugu#174]
**Question**
I am setting a window handler using `js.FuncOf`. This handler is changing the struct, but the page is not updating. Normally I use an event's `EventEnv`, but I don't have an event. How can I get the page to update?

**Comment by bradleypeabody** [comment]
You can keep a copy of the EventEnv from the Init() method's InitCtx  and use that to tell it to update.  A single EventEnv is valid for the lifetime of the application.

**Comment by Nv7-GitHub** [comment]
For some reason, the InitCtx EventEnv is `nil`. Do you know why this is?

**Comment by bradleypeabody** [comment]
Your main_wasm.go might be out of date.  If you take a look here https://github.com/vugu/vugu/blob/master/gen/parser-go-pkg.go#L278 the the BuildEnv now gets an instance of EventEnv.  If you (re)move your main_wasm.go and let it get re-created, that will likely fix the problem (or alternatively make that edit manually).
