### ISSUE TITLE
zsh: command not found: vgrun

### ISSUE THREAD

**Issue by Virgil-N** [vugu/vugu#184]
**Question**
After run command "vgrun -install-tools"; I get "zsh: command not found: vgrun".

I'm using mac book M1, go version is go1.16rc1.

**Comment by bradleypeabody** [comment]
I suspect `~/go/bin` is not in your PATH.   Try `echo $PATH` and see what outputs. See https://golang.org/doc/install#install and this has some info on setting zsh environment variables: https://stackoverflow.com/a/18077919

**Comment by Virgil-N** [comment]
> I suspect `~/go/bin` is not in your PATH.   Try `echo $PATH` and see what outputs. See https://golang.org/doc/install#install and this has some info on setting zsh environment variables: https://stackoverflow.com/a/18077919

But I had set gopath and goroot in my .zshrc file and I can use go command normaly.

**Comment by Virgil-N** [comment]
> I suspect `~/go/bin` is not in your PATH.   Try `echo $PATH` and see what outputs. See https://golang.org/doc/install#install and this has some info on setting zsh environment variables: https://stackoverflow.com/a/18077919

You say $path?
I will try.

**Comment by Virgil-N** [comment]
> I suspect `~/go/bin` is not in your PATH. Try `echo $PATH` and see what outputs. See https://golang.org/doc/install#install and this has some info on setting zsh environment variables: https://stackoverflow.com/a/18077919

I typed "echo $path", get this: 
/Users/virgil/.nvm/versions/node/v15.8.0/bin /opt/homebrew/opt/ncurses/bin /opt/homebrew/opt/icu4c/sbin /opt/homebrew/opt/icu4c/bin /opt/homebrew/bin /opt/homebrew/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Library/Apple/usr/bin

Does this means there is no problems in my $path ?

**Comment by Virgil-N** [comment]
> I suspect `~/go/bin` is not in your PATH. Try `echo $PATH` and see what outputs. See https://golang.org/doc/install#install and this has some info on setting zsh environment variables: https://stackoverflow.com/a/18077919

You are right. I fixed it.
Thanks!

**Comment by fabienblin** [comment]
I have the same error with bash running `vgrun -install-tools` , vgrun command not found after `go get -u -v github.com/vugu/vgrun` which worked fine to download vugu.

My $PATH is set in .profile and contains 
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/lib/go-1.19/bin:/home/fabien/go/bin`
using `export PATH=$PATH:$(go env GOROOT)/bin:$(go env GOPATH)/bin`

When i browse GOROOT/bin and GOPATH/bin there is no vgrun binary,  `find . -type f -name 'vgrun'` didn't find eighther.

I'm on Golang 1.19.8, Raspberry Pi 4 b (arm64), Debian (freshly installed)

**Comment by owenwaller** [comment]
Hi @fabienblin 

Thanks for this.

Not entirely sure. The $PATH you have listed looks ok (at first glance). 
Where did you run the `find . -type f -name 'vgrun'` from?

**Comment by fabienblin** [comment]
Hello Friend,
I did it in home then root.
I was able to find the sources of vugu inside subdirectories of gopath, which allowed me to compile with go build -o $gopath/bin/vgrun .
Now my project works and I got the server up and running.

**Comment by owenwaller** [comment]
@fabienblin 

Glad you found work around, but I think I have the correct fix.

I think, as you are using Go 1.19 you are using a module aware version of `go get` and in this case meaning of the `-u` flag is different.

Can you please remove your locally built `vgrun` binary and try installing `vgrun` like this:

`go install github.com/vugu/vgrun@latest`

And let us know if that works for you?

My reasoning goes like this. 

In module aware mode (which is the default since go1.16) `go get` has changed the meaning of the `-u` flag to this:
```
The -u flag instructs get to update modules providing dependencies
of packages named on the command line to use newer minor or patch
releases when available.

The -u=patch flag (not -u patch) also instructs get to update dependencies,
but changes the default to select patch releases.

When the -t and -u flags are used together, get will update
test dependencies as well.
```

from `go help module-get`, where as previously (in the GOPATH days) it was this:

```
The -u flag instructs get to use the network to update the named packages
and their dependencies. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.
```

from `go help gopath-get`

So, as you are in module aware mode you are actually doing an update of the dependencies, not building and installing the `vgrun` binary. To do that you need to use `go install` when running modules.

If that works, then we have need to update the documentation.

Thanks
