### ISSUE TITLE
Getting started docs fail with Go v1.16

### ISSUE THREAD

**Issue by owenwaller** [vugu/vugu#186]
**Describe the bug**
I am attempting to follow the "Getting Started" guide at: https://www.vugu.org/doc/start, but am seeing an this:

```2021/02/24 19:13:00 Starting HTTP Server at "127.0.0.1:8844"
WasmCompiler: Successful generate
WasmCompiler: build error: exit status 1; full output:
0_components_vgen.go:7:8: missing go.sum entry for module providing package github.com/vugu/vjson (imported by github.com/vugu-examples/simple); to add:
	go get github.com/vugu-examples/simple
../go/pkg/mod/github.com/vugu/vugu@v0.3.3/build-env.go:7:2: missing go.sum entry for module providing package github.com/vugu/xxhash (imported by github.com/vugu/vugu); to add:
	go get github.com/vugu/vugu@v0.3.3
```

At the `vgrun devserver.go` step.

Browsing to http://127.0.0.1:8844/ shows the same error on the web page.

**Software Versions**
Vugu version: v0.3.3 (HEAD @ 0b6c4630ee99bddc07939f4443c40976cc227289)
Go version: 1.16
Browser and version:  Chromium Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.13 (64-bit)

**To Reproduce**
As per the Getting Started instructions the sequence was:

1) Install go v1.16
2) `go get -u github.com/vugu/vgrun`
3) `vgrun -install-tools`
4) `mkdir ~/vugu-example`
5) `cd ~/vugu-example/`
6) `vgrun -new-from-example=simple .`
7) `vgrun devserver.go`

Step (7) then fails with:
```
2021/02/24 19:03:44 initial build error: build error: exit status 1; full output:
devserver.go:9:2: no required module provides package github.com/vugu/vugu/devutil; to add it:
	go get github.com/vugu/vugu/devutil
```

Which leads to:

8) `go get -u -d github.com/vugu/vugu/devutil`
9) `go install github.com/vugu/vugu/devutil`
10) `vgrun devserver.go`

Which should now produce the above error on the terminal and in the browser.

**Expected behavior**
No error and the example vugu application running in the browser - as per the Getting Started instructions

**Additional Notes**
My `go env` is:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/owen/.cache/go-build"
GOENV="/home/owen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/owen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/owen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/owen/sdk/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/owen/sdk/go1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3850928410=/tmp/go-build -gno-record-gcc-switches"
```

Any help appreciated, as I'm trying to get started with vugu, before attempting to build it from source.

The `github.com/vugu/vjson` is missing in the `go.sum` but I'm not sure if a `go mod tidy` is required somewhere or a `go get -u github.com/vugu-examples/simple` is required.

**Comment by bradleypeabody** [comment]
@owenwaller I'm pretty sure it's related to this change: https://golang.org/doc/go1.16#go-command
> Module-aware mode is enabled by default, regardless of whether a go.mod file is present in the current working directory or a parent directory. More precisely, the GO111MODULE environment variable now defaults to on. To switch to the previous behavior, set GO111MODULE to auto.

This definitely needs a fix in Vugu and I'll review that, but for the moment can you confirm that setting GO111MODULE to `auto` solves the issue?  (`export GO111MODULE=auto` for Mac/Linux)

**Comment by owenwaller** [comment]
Hi,

I have just tried this and I get exactly the same result. I agree with you that this is a change in the `go` command's behaviour with modules, but this looks like a module is not referenced (when it should be) in the example.

The only odd thing I can see in the terminal is that the `go get -u -d github.com/vugu/vugu/devutil` is the only time `go get` actually gets `github.com/vugu/vugu v0.3.3`. But, at least according to the "Getting Started" guide, this is an unnecessary `go get` step. Could this be related?

The command sequence was
```
export GO111MODULE=auto
go get -u github.com/vugu/vgrun
vgrun -install-tools
mkdir ~/vugu-example
cd ~/vugu-example/
vgrun -new-from-example=simple .
vgrun devserver.go
go get -u -d github.com/vugu/vugu/devutil
go install github.com/vugu/vugu/devutil
vgrun devserver.go
```
Note: When I ran the sequence I made sure I had deleted the `vugu`, `vgrun` and the example source directories from disk and, from the module and download caches.

`go env` produces:

```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/owen/.cache/go-build"
GOENV="/home/owen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/owen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/owen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/owen/sdk/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/owen/sdk/go1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/owen/vugu-example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2579881807=/tmp/go-build -gno-record-gcc-switches"

```

As before `vgrun devseerver.go` gives me

```
vgrun devserver.go 
2021/03/01 16:08:10 Starting HTTP Server at "127.0.0.1:8844"
WasmCompiler: Successful generate
WasmCompiler: build error: exit status 1; full output:
0_components_vgen.go:7:8: missing go.sum entry for module providing package github.com/vugu/vjson (imported by github.com/vugu-examples/simple); to add:
	go get github.com/vugu-examples/simple
../go/pkg/mod/github.com/vugu/vugu@v0.3.3/build-env.go:7:2: missing go.sum entry for module providing package github.com/vugu/xxhash (imported by github.com/vugu/vugu); to add:
	go get github.com/vugu/vugu@v0.3.3

2021/03/01 16:08:14 MainWasmHandler: Execute error:
WasmCompiler: build error: exit status 1; full output:
0_components_vgen.go:7:8: missing go.sum entry for module providing package github.com/vugu/vjson (imported by github.com/vugu-examples/simple); to add:
	go get github.com/vugu-examples/simple
../go/pkg/mod/github.com/vugu/vugu@v0.3.3/build-env.go:7:2: missing go.sum entry for module providing package github.com/vugu/xxhash (imported by github.com/vugu/vugu); to add:
	go get github.com/vugu/vugu@v0.3.3
WasmCompiler: Successful generate
WasmCompiler: build error: exit status 1; full output:
0_components_vgen.go:7:8: missing go.sum entry for module providing package github.com/vugu/vjson (imported by github.com/vugu-examples/simple); to add:
	go get github.com/vugu-examples/simple
../go/pkg/mod/github.com/vugu/vugu@v0.3.3/build-env.go:7:2: missing go.sum entry for module providing package github.com/vugu/xxhash (imported by github.com/vugu/vugu); to add:
	go get github.com/vugu/vugu@v0.3.3
```

And I see the same error if I browse to http://localhost:8844/.

As a suggestion it may be worth putting the "Getting Started" command sequence in a Travils-CI file, so that it's executed on every push. That would at least trap any breaking mistakes in these instructions going forward.

Owen

**Comment by owenwaller** [comment]
Hi,

Just out of curiosity, I've just tried this:

```
cd ~/vugu-example
go mod tidy
```
So see if the go module tool chain can resolve the missing module entries. The output was:

```
go: downloading github.com/vugu/vjson v0.0.0-20200505061711-f9cbed27d3d9
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/vugu/xxhash v0.0.0-20191111030615-ed24d0179019
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
```
So that resolves the `go.sum` module entry for `vjson` and `xxxhash`

If I then run `vgrun devserver.go` things work as expected. The output is:

```
2021/03/01 16:48:31 Starting HTTP Server at "127.0.0.1:8844"
WasmCompiler: Successful generate
WasmCompiler: Successful generate
WasmCompiler: Successful build
WasmCompiler: Successful build
WasmCompiler: Successful generate
WasmCompiler: Successful build
```
and I can see the vugu app example page in the browser.

What I'll try now, is to unset GO111MODULE (so back to the go v1.16 default of on) and see if the `go mod tidy` also resolves things.

Owen

**Comment by owenwaller** [comment]
Hi,

If I unset GO111MODULE (the go v1.16 default), and run things again from a clean disk then, yes, with the addition of a `go mod tidy` before running `vgrun devserver.go` everything works.

The command sequence was:

```
unset GO111MODULE
go get -u github.com/vugu/vgrun
vgrun -install-tools
mkdir ~/vugu-example
cd ~/vugu-example/
vgrun -new-from-example=simple .
vgrun devserver.go
go get -u -d github.com/vugu/vugu/devutil
go install github.com/vugu/vugu/devutil
vgrun devserver.go       <--- this will fail as before
go mod tidy
vgrun devserver.go       <--- this should now work
```

So could fixing this be as simple as:

a) Adding a `go.sum` file in for the example project? Looking in https://github.com/vugu/vugu it appears to be missing.
b) Possibly updating the Vugu "Getting Started" guide to mention `go get`ing `github.com/vugu/devutil` and possibly running `go mod tidy`?

I'm happy to submit a PR for (b) if you want. I've leave (a) to you as you may have specific versions for the modules used by the example in mind.

Owen

**Comment by bradleypeabody** [comment]
Interesting, it seems like it's choking on not having a go.sum on github.com/vugu/vjson and github.com/vugu/xxhash

This looks related (indeed I think it's the cause): https://github.com/golang/go/issues/44129

It's probably not a big deal to add the go.sum file to those projects, but I am curious as to why this is suddenly a requirement.  And also I'm wondering if just those two packages will fix it, or if there will be some other dependency problem as well.

**Comment by owenwaller** [comment]
Hi,

It seems to be possible that this is bug in the go toolchain. The error message is the same and the circumstances seem to be similar.

I assume you don't see this behaviour on versions of go before 1.16? I see that the Travis CI builds ask for go v1.14 and v1.15. What happens if you try go v1.16 there?

Poking around in my module cache I can see this - which may or may not be related.

```
cd ~/go/pkg/mod/github.com/vugu
ls -l
total 16
dr-xr-xr-x  2 owen owen 4096 Mar  1 17:26 vgrun@v0.0.0-20200826222056-7658e8a51788
dr-xr-xr-x  2 owen owen 4096 Mar  1 17:28 vjson@v0.0.0-20200505061711-f9cbed27d3d9
dr-xr-xr-x 16 owen owen 4096 Mar  1 17:27 vugu@v0.3.3
dr-xr-xr-x  2 owen owen 4096 Mar  1 17:28 xxhash@v0.0.0-20191111030615-ed24d0179019
```
So I have no write permissions on the directory tree which will prevent any update. I'm not sure if this is a change in the go tooling or a mistake, but it is odd as it means nothing (short of executing as root) can ever change/update/delete anything in this tree.

Other directories under `~/go/pkg/mod/github.com/` are similar so this is not a vugu issue.

As I don't have go 1.15 installed, what do you see?

**Comment by bradleypeabody** [comment]
> I assume you don't see this behaviour on versions of go before 1.16?
I have not run into this before, no.

I actually just upgraded to 1.16 I'm getting the same error. Previously on Go 1.15 this worked correctly.

I updated go.mod and go.sum in here http://github.com/vugu-examples/simple to include vjson. And now it prompts on each of the packages to run `go mod download`.  But once you've done that for each one it then continues.

Probably both [this page](https://www.vugu.org/doc/start) should mention `go mod tidy` and `vgrun`'s -new-from-example workflow could also shell out and run `go mod tidy` automatically after downloading the example.  Let me know if you want to volunteer to do PRs for those.

**Comment by owenwaller** [comment]
Hi,

Hum, now things appear to be very broken. In order to see if your push of a `go.sum` to the example apps repo made any change I've done this. 

Starting with deleting my module cache to make sure I am in a clean state and then attempting to do the command sequence that I have run previously, but updating it based on the errors and advice the go tool spits out.

```
$ go clean -modcache
$ go get -u github.com/vugu/vgrun
go: downloading github.com/vugu/vgrun v0.0.0-20200826222056-7658e8a51788
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading golang.org/x/sys v0.0.0-20200427175716-29b57079015a
go: downloading golang.org/x/sys v0.0.0-20210303074136-134d130e1a04
$ vgrun -install-tools
2021/03/03 22:36:38 Installing vugugen
2021/03/03 22:36:39 Installing vgrgen
$ vgrun -new-from-example=simple .
2021/03/03 22:37:16 Running command: [git clone -q --depth=1 https://github.com/vugu-examples/simple .]
2021/03/03 22:37:17 Removing .git directory from example
$ vgrun devserver.go 
2021/03/03 22:37:27 initial build error: generate error: exit status 1; full output:
go: github.com/vugu/vjson@v0.0.0-20191111004939-722507e863cb: missing go.sum entry; to add it:
	go mod download github.com/vugu/vjson
$ go mod download github.com/vugu/vjson
$ vgrun devserver.go 
2021/03/03 22:37:56 initial build error: build error: exit status 1; full output:
devserver.go:9:2: missing go.sum entry for module providing package github.com/vugu/vugu/devutil; to add:
	go mod download github.com/vugu/vugu
$ go mod download github.com/vugu/vugu
$ vgrun devserver.go 
2021/03/03 22:38:55 initial build error: build error: exit status 1; full output:
devserver.go:9:2: no required module provides package github.com/vugu/vugu/devutil; to add it:
	go get github.com/vugu/vugu/devutil
$ go get github.com/vugu/devutil
go get: module github.com/vugu/devutil: git ls-remote -q origin in /home/owen/go/pkg/mod/cache/vcs/9412f74079139234e1c6e6cdc11d26c5fabc5f9c5047c9ab3d05276f450454d7: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```
Which is weird, as the URL is not malformed as far as I can see.

But you are correct, it would see that go.sum needs to be added in more than two places.

Owen

**Comment by owenwaller** [comment]
Hi,

Opps my mistake, I was trying to download the module `github.com/vugu/devutil` *not* the correct `github.com/vugu/vugu/devutil`.

Once I download the correct module then, yes, it all works. The alternative command sequence is:

```
$go clean -modcache
$ go get -u github.com/vugu/vgrun
go: downloading github.com/vugu/vgrun v0.0.0-20200826222056-7658e8a51788
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading golang.org/x/sys v0.0.0-20200427175716-29b57079015a
go: downloading golang.org/x/sys v0.0.0-20210303074136-134d130e1a04
$ vgrun -install-tools
2021/03/03 22:53:07 Installing vugugen
2021/03/03 22:53:09 Installing vgrgen
$ cd vugu-example/
$ vgrun -new-from-example=simple .
2021/03/03 22:53:28 Running command: [git clone -q --depth=1 https://github.com/vugu-examples/simple .]
2021/03/03 22:53:29 Removing .git directory from example
$ vgrun devserver.go 
2021/03/03 22:53:38 initial build error: generate error: exit status 1; full output:
go: github.com/vugu/vjson@v0.0.0-20191111004939-722507e863cb: missing go.sum entry; to add it:
	go mod download github.com/vugu/vjson
$ go mod download github.com/vugu/vjson
$ vgrun devserver.go 
2021/03/03 22:53:57 initial build error: build error: exit status 1; full output:
devserver.go:9:2: missing go.sum entry for module providing package github.com/vugu/vugu/devutil; to add:
	go mod download github.com/vugu/vugu
$ go mod download github.com/vugu/vugu
$ vgrun devserver.go 
2021/03/03 22:54:13 initial build error: build error: exit status 1; full output:
devserver.go:9:2: no required module provides package github.com/vugu/vugu/devutil; to add it:
	go get github.com/vugu/vugu/devutil
$ go get github.com/vugu/vugu/devutil
go: downloading github.com/vugu/vugu v0.3.3
go get: upgraded github.com/vugu/vjson v0.0.0-20191111004939-722507e863cb => v0.0.0-20200505061711-f9cbed27d3d9
go get: upgraded github.com/vugu/vugu v0.2.1 => v0.3.3
$ vgrun devserver.go     <---- this will then work as expected.
```

Happy to do the PRs if you want to point me in the right direction.

Owen

**Comment by bradleypeabody** [comment]
Ah, okay great.  Glad that's working.

So just to confirm, you do `vgrun -new-from-example=simple .`, and then `go mod tidy`, followed by `vgrun devserver.go` it works properly, yes?

If so, then I think adding another step right after this https://github.com/vugu/vgrun/blob/master/vgrun-main.go#L127 to run `go mod tidy` would probably help smooth the experience a lot.

You should be able to clone the https://github.com/vugu/vgrun repo, make the change, `go install` your version and test it, and if it's all good make a PR.

**Comment by owenwaller** [comment]
Hi,

No adding a simple `go mod tidy` before running `vgrun devserver.go` is not the fix, now that the `go.sum` has been added to the example application repo.

I've just tried things again, and issuing a `go mod tidy` before the `vgrun devserver.go` does not resolve the problem.

The output is:

```
$ go clean -modcache
$ go get -u github.com/vugu/vgrun
go: downloading github.com/vugu/vgrun v0.0.0-20200826222056-7658e8a51788
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading golang.org/x/sys v0.0.0-20200427175716-29b57079015a
go: downloading golang.org/x/sys v0.0.0-20210304124612-50617c2ba197
$ vgrun -install-tools
2021/03/04 14:04:25 Installing vugugen
2021/03/04 14:04:27 Installing vgrgen
$ cd vugu-example/
$ vgrun -new-from-example=simple .
2021/03/04 14:04:41 Running command: [git clone -q --depth=1 https://github.com/vugu-examples/simple .]
2021/03/04 14:04:41 Removing .git directory from example
$ vgrun devserver.go      <---- this will fail
2021/03/04 14:04:54 initial build error: generate error: exit status 1; full output:
go: github.com/vugu/vjson@v0.0.0-20191111004939-722507e863cb: missing go.sum entry; to add it:
	go mod download github.com/vugu/vjson
$ go mod tidy      <---- attempt to fix with a go mod tidy
$ vgrun devserver.go    <---- still broken 
2021/03/04 14:05:03 initial build error: build error: exit status 1; full output:
devserver.go:9:2: no required module provides package github.com/vugu/vugu/devutil; to add it:
	go get github.com/vugu/vugu/devutil
$ go get github.com/vugu/vugu/devutil     <----- do the go get
go: downloading github.com/vugu/vugu v0.3.3
go get: added github.com/vugu/vugu v0.3.3
$ vgrun devserver.go    <---- and we are still broken 
2021/03/04 14:10:05 Starting HTTP Server at "127.0.0.1:8844"
WasmCompiler: Successful generate
WasmCompiler: Successful generate
WasmCompiler: build error: exit status 1; full output:
0_components_vgen.go:7:8: missing go.sum entry for module providing package github.com/vugu/vjson (imported by github.com/vugu-examples/simple); to add:
	go get github.com/vugu-examples/simple
../go/pkg/mod/github.com/vugu/vugu@v0.3.3/build-env.go:7:2: missing go.sum entry for module providing package github.com/vugu/xxhash (imported by github.com/vugu/vugu); to add:
	go get github.com/vugu/vugu@v0.3.3
```
If I now repeat the sequence from https://github.com/vugu/vugu/issues/186#issuecomment-790138601 things still work.

The critical steps are to add:
```
go mod download github.com/vugu/vjson
go mod download github.com/vugu/vugu
go get github.com/vugu/vugu/devutil
```
before the `vgrun devserver.go`

Although this works, I am not sure having `vgrun` do a `go get` of the `devutils` package feels correct. Given that the original "Getting Started" instructions don't mention needing to do a `go get githug.com/vugu/vugu/devtils` I wonder if there is also an issue with this package?

I'm also surprised that the `go mod tidy` now doesn't solve things since the `go.sum` was added to the example apps repo.

Owen

**Comment by bradleypeabody** [comment]
I see.  Yeah the core of the issue seems to be that now the Go 1.16 compiler wants you to explicitly download any missing packages (whereas it was doing this automatically before).  This looks like the result of: https://golang.org/doc/go1.16#go-command
> Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.

Unfortunately what's happening here is there are multiple build paths each with their own dependencies.  `go mod tidy` is looking at the directory as a package.  `devserver.go` is a standalone file (which `go mod tidy` is not seeing due to `// +build ignore`), and furthermore I'm concerned about the fact that when you browse to the page and it tries to compile main.wasm it's a different set of dependencies than is required to run devserver.go. Since this other build command is being run automatically (from code in devutil), there's no easy way to get in there and run the commands it's asking for.  So I suspect that even with the set of commands you list above this won't be the end of it.

I think the overall solution is going to be switching over to having a separate build script (probably also a .go file) that builds both the frontend and the backend, and that script being called both by the user to build the project and by the server when main.wasm needs to be rebuilt.   That way it's just one path to build everything and has the same dependencies.   Unfortunately I do have that ready right this moment.

All that said, probably the simplest immediate solution is to warn new users in the documentation https://www.vugu.org/doc/start that they will need to run some `go mod download` or `go get` commands when using Go 1.16 and higher (I'm not sure if we should list them out, the compiler will already do that for them).

Note that `go mod download` does a bit better than `go mod tidy` because it only downloads dependencies and doesn't remove ones that are "no longer needed" (which it can't know because it is not looking at the devserver.go and wasm build paths).

Those are my thought on this so far.

**Comment by owenwaller** [comment]
Hi,

Hum. There seems to be no great solution to this. Either we wait and see what happens with the go tool itself, or we try to work around it.

Have you tried to file this as an explicit issue with the Go team?

If we wait, which I'm tempted to do as we'll have more information, in case to Go team change this behaviour in a future 1.6.1 release then I would change the docs.

If I was going to change the docs I would make it explicit and say: "If you have go v1.16 then you need to do this...." and then layout the commands exactly as we think they should be at the minute. I'd rather be explicit with the commands, as like me, folks may be new to vugu and go module experience varies across the community. 

We can always revise the docs later to correct.

It may well also be worth trying to automate this process via Travis-CI so that if adding `go.sum` files starts breaking things or causes the "Getting started" instructions to fail it would be caught early.

What do you think? 

I can think of other approaches that would make `vgrun` more intelligent and respond the the command line requests for missing packages by executing the `go mod download` or `go get` but that seems like a bit to much magic at the minute.

Can you explain exactly how the build system for vugu works? I can have a think to see if there is a different approach.

Owen

**Comment by owenwaller** [comment]
Hi,

Just to confirm that having upgraded to go v1.16.2 I see the same behaviour.
The instructions at https://github.com/vugu/vugu/issues/186#issuecomment-790138601 still appear to be required.
Given the minor changes from go v1.16 I guess this result is to be expected.

Owen

**Comment by bradleypeabody** [comment]
@owenwaller Thanks, yeah this is definitely a bummer.

Overall I think the solution is going to be to move toward a more consistent build setup where the backend and frontend are built from a single script.  This way the user can just run that one command from the command line, deal with any error messages (go get, etc.) and then be done with it.  The earlier assumption that we could `go build` from inside another executable and have Go deal with the dependencies automatically seems to no longer be a workable solution.

It's probably all for the best anyway, since the single-script approach is probably better anyway.  It's just inconvenient with the various things that are setup at the moment.

Some work is being done here: https://github.com/vugu-examples/taco-store and I'll try to ensure this new build setup is included there soon and maybe then the simple Getting Started example can just be switched over to use this new structure.

**Comment by arvryna** [comment]
@owenwaller: The issue is fixed and tested. Please let us know if you face any further difficulties.

**Comment by owenwaller** [comment]
@arvryna Many thanks. I'll have a go when I get a chance. My team has what would make a good use case for Vugu coming up so that may well be the test.

**Comment by owenwaller** [comment]
As I opened the issue....

This is all fixed. We don't have any problems using vugu with Go 1.20 and v1.21.
