### ISSUE TITLE
Support script source

### ISSUE THREAD

**Issue by lordnynex** [vugu/vugu#20]
(Sorry if this is already supported. I don't see it in the docs and the issue tracker doesn't seem to have a question template. Please close the request if I've missed something obvious.)

**Is your feature request related to a problem? Please describe.**
I've not spent much time with Vugu yet but the idea that .vugu files are polyglot makes me apprehensive. I'd prefer to use the full configured feature set of my IDE by writing Go code in a a `.go` suffixed file. 

**Describe the solution you'd like**
`<script type="application/x-go" src="./path/to/component.go">`

**Describe alternatives you've considered**
Writing an IDE plugin. I don't have the time or desire to do this. 

**Additional context**
I have not considered how this would impact your special naming conventions.

**Comment by bradleypeabody** [comment]
You can achieve this same functionality by adding another file right along side your component, in the same Go package.

For example, _root.vugu_ can contain your HTML markup.  The code generator produces _root.go_.  But then any Go code that you would have put in a `<script type="application/x-go">` tag you can instead put in something like _root-logic.go_ or similar.  The examples show that you would define structs like RootData to house data for your component - and this can go in any file in the package. 
 Perhaps there should be a naming convention for this sort of file ("root-logic.go" is just the first thing that came to mind).  

I believe this addresses the issue you're describing.  Let me know if not.

**Comment by bradleypeabody** [comment]
I've documented this here: http://www.vugu.org/doc/files/code

I think that fully addresses the concern.  Closing this issue, feel free to open it back up if you think something else is needed on it.
