### ISSUE TITLE
Getting started problem...

### ISSUE THREAD

**Issue by pienaahj** [vugu/vugu#210]
**Question**
When trying to start out with "go get -u github.com/vugu/vgrun " in the start guide, go get -u github.com/vugu/vgrun fails with:
Response : 
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Suggested Changes**
I don't know enough about Go to figure a way around this.
If possible, please amend the startup guide to use go install or please provide help on workaround.

**Additional context**
go version 1.17

Much appreciated.

**Comment by bprfh** [comment]
Golang can do two things when getting packages:
1. Get the package source code
2. Build and Install the binaries in the GOPATH/bin directory so you can use them.
In version 1.17 golang changed these two things to seperate commands: 
1. "go get" will get the source code 
2. "go install" will compile the source code and place the binaries in the GOPATH/bin directory 
That being said, the message you getting is just a message that this is deprecated and will be removed, I just tried it with go1.17 and it still works, but if not you can just use "go install" instead.

**Comment by bprfh** [comment]
Made a pr for the website to change the directions:
https://github.com/vugu/vugu-site/pull/8

**Comment by nexlight101** [comment]
Thank you for the feedback sir, much appreciate.

**Comment by nexlight101** [comment]
Hi just some feedback.  Please excuse my lack of experience or knowledge..
This is the output from start to working 

[vugu_install.txt](https://github.com/vugu/vugu/files/7030726/vugu_install.txt)

if I stuffed up some steps, please forgive...

**Comment by delgoden** [comment]
not working vgrun -install-tools

**Comment by delgoden** [comment]
I'm solved this problem

**Comment by owenwaller** [comment]
For the vugu v1.0 release, I don't think we'll support anything other than the last two Go versions - currently v1.20 and v1.21. Both of which support Go modules.

Go modules are now also well established in an use by the Go Community, so supporting any pre-module approach isn't practical.

**Comment by pienaahj** [comment]
Thanks for feedback Owen. Much appreciated. HendrikSent from my iPhoneOn 02 Nov 2023, at 14:03, Owen Waller ***@***.***> wrote:﻿
Closed #210 as completed.
