### ISSUE TITLE
With the devserver where can I place local assets like images?

### ISSUE THREAD

**Issue by andrewarrow** [vugu/vugu#213]
is there a standard directory like `assets` or something where I can place an image I want my devserver to serve with a path like 
http://localhost:8844/assets/my-image.png ?

**Comment by andrewarrow** [comment]
i ended up adding:

```
        mux.Exact("/assets/b3.png", devutil.StaticFilePath("assets/b3.png"))
```

but there must be a better way than having to do this `Exact` match for each image...

**Comment by sorenisanerd** [comment]
See https://github.com/vugu-examples/simple/blob/master/devserver.go#L23

Adding that line will expose the whole directory. Try e.g. http://localhost:8844/devserver.go and you'll see.

**Comment by andrewarrow** [comment]
ah thank u!
