### ISSUE TITLE
Any new features or further progress about Vugu ?

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#214]
Anyway... it works enough for me now .
Thanks .

**Comment by bradleypeabody** [comment]
Yeah, no word at the moment, but more logistics are still in progress to get an official sponsor. That will definitely help move things along.

**Comment by andrewarrow** [comment]
this is great. I work for a public company that uses go heavily but also tons of typescript. Would love to move away from react and webpack and typescript and towards all go.

**Comment by bradleypeabody** [comment]
Yup, I hear you!

**Comment by owenwaller** [comment]
I think we can can close this. See #246
