### ISSUE TITLE
Vugu (Go) framework: @click event is not working

### ISSUE THREAD

**Issue by VanCoppenolleWout** [vugu/vugu#215]
This is an example as shown in the Vugu docs, yet it doesn't seem to work. https://www.vugu.org/doc/dom-events

github is not recognizing my code so here's a screenshot -> https://ibb.co/jHXcL34

**Comment by andrewarrow** [comment]
what do you see on the screen when this code runs? Can I see a screenshot of the javascript console in the browser too?

**Comment by VanCoppenolleWout** [comment]
> what do you see on the screen when this code runs? Can I see a screenshot of the javascript console in the browser too?

Hi Andrew, when i run that code in a new and fresh project it works. Just not in mine. I can't seem to figure out what goes wrong. 
screenshot -> https://ibb.co/K9qSngP

my project: https://github.com/VanCoppenolleWout/VuguMovies/tree/develop

**Comment by andrewarrow** [comment]
oh try starting with the working example of https://github.com/vugu/vugu/issues/216 "taco-store". Use it's file structure and change it step by step to your site vs. trying to start a whole complex site from the ground up.
