### ISSUE TITLE
is vugu-site example end result just static html?

### ISSUE THREAD

**Issue by andrewarrow** [vugu/vugu#216]
I started looking at the big example that is:

https://github.com/vugu/vugu-site

And it's great. I learned a lot about how to make a bigger project in vugu than just the default small example. But am I missing something or does vugu-site just render static html and doesn't actually expose a final wasm to the user?

I ran `vgrun -1 server -build` and looked at all the files in the output directory and, it's just html right?

Is there an example as large and complex as vugu-site but with more clicks and user interactions that force the use of a wasm? Thanks!

**Comment by bradleypeabody** [comment]
@andrewarrow You're correct about the Vugu site - originally it did output wasm but since the site is just static anyway it was changed to use Vugu to output static HTML.

For an example of a more complex, dynamic app, have a look here: https://github.com/vugu-examples/taco-store

**Comment by andrewarrow** [comment]
thanks!

**Comment by andrewarrow** [comment]
oh, when i try and run taco:

```
os/taco-store $ ./build.sh
os/taco-store $ ls -l bin   
total 13024
-rwxr-xr-x  1 aa  staff  6664976 Jan 24 09:11 server
os/taco-store $ bin/server                              
2022/01/24 09:11:45 Starting HTTP Server at "127.0.0.1:8844"
2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
11111 /
2022/01/24 09:11:47 go run build-frontend.go - err: <nil>
2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
11111 /css/main.css
2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
11111 /wasm_exec.js
2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
11111 /index.wasm
^C
os/taco-store $ ls dist/css/main.css 
dist/css/main.css
os/taco-store $ ls dist/            
css		index.wasm
```

wasm_exec.js is 404? I just get spinner.

**Comment by andrewarrow** [comment]
oh back in business with `cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .`

**Comment by VanCoppenolleWout** [comment]
> oh, when i try and run taco:
> 
> ```
> os/taco-store $ ./build.sh
> os/taco-store $ ls -l bin   
> total 13024
> -rwxr-xr-x  1 aa  staff  6664976 Jan 24 09:11 server
> os/taco-store $ bin/server                              
> 2022/01/24 09:11:45 Starting HTTP Server at "127.0.0.1:8844"
> 2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
> 11111 /
> 2022/01/24 09:11:47 go run build-frontend.go - err: <nil>
> 2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
> 11111 /css/main.css
> 2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
> 11111 /wasm_exec.js
> 2022/01/24 09:11:47 FrontendHandler starting with dist dir: /Users/aa/os/taco-store/dist
> 11111 /index.wasm
> ^C
> os/taco-store $ ls dist/css/main.css 
> dist/css/main.css
> os/taco-store $ ls dist/            
> css		index.wasm
> ```
> 
> wasm_exec.js is 404? I just get spinner.

when i try to run it I get the same output but a different error: 
`Uncaught (in promise) ReferenceError: Go is not defined
    at (index):28:15`
The very same thing happens with the taco-store project.
