### ISSUE TITLE
Full-HTML Mode for taco-store example

### ISSUE THREAD

**Issue by andrewarrow** [vugu/vugu#217]
I'm having trouble getting the taco-store root.vugu:

https://github.com/vugu-examples/taco-store/blob/main/ui/pages/root.vugu

to be more like the vugu-site Full-HTML Mode one:

https://github.com/vugu/vugu-site/blob/master/app/components/root.vugu

I get `error parsing "root.vugu": element "div" found after we already have a mount element`

https://github.com/vugu/vugu/blob/24d8d4332371618c6f2b8881ae9f8d52fab8e3ca/gen/parser-go.go#L449

When I make the root.vugu the same as vugu-site. Any ideas?

**Comment by owenwaller** [comment]
I am going to close this issue. I now think "FullHTML" mode isn't a thing any more. Going forward this is going to be the default.

See #260 - specifically the new `vgutil` tool that is in preparation. And the [new wiki page](https://github.com/vugu/vugu/wiki/Building-With-Go-and-Deploying-with-nginx) that shows you how make vugu work if you have write your own `index.html` file.
