### ISSUE TITLE
Add IPA to Readme 

### ISSUE THREAD

**Issue by shilangyu** [vugu/vugu#24]
Just like Vue.js. ATM I have no idea how to pronounce vugu.
Thanks!

**Comment by bradleypeabody** [comment]
Lol, that makes two of us!

But okay, valid point.  I pronounce it "voo-goo".

I unfortunately know very little about IPA - do you know how "voo-goo" would be written?  Per [ipachart.com](http://www.ipachart.com/) it seems like it would be "vɞgɞ".  But on [this tool](https://itinerarium.github.io/phoneme-synthesis/) it pronounces "vugu" correctly (like "voo-goo").

**Comment by id8872** [comment]
If it's anything like fugu, the deadly puffer fish of Simpson's episode 02-24 then it seems /ˈvuː.ɡuː/
https://en.wiktionary.org/wiki/fugu

**Comment by bradleypeabody** [comment]
Excellent, thank you.  I've updated the [README](https://github.com/vugu/vugu/blob/master/README.md).
