### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by intel352** [vugu/vugu#243]
Last update on the homepage shows `2020-09-13`, is this project abandoned?

**Comment by bradleypeabody** [comment]
Nope, this project is not abandoned, just hasn't had the love it deserves in a while.  There are still plans in the works to get more effort devoted to updating and improving, etc. but so far that hasn't yet materialized.  In the mean time I do what I can on the side and PRs are welcome to fix critical things.

**Comment by owenwaller** [comment]
@bradleypeabody This is beginning to sound like you need some help. 

Do you have an idea of where you need help and what needs to be done?

**Comment by intel352** [comment]
> Btw, is this project abandoned now?

It's not officially abandoned yet, it's just not under active development. Since this thread was started, the repo received a pull request that was merged, so the maintainer is still somewhat available.

**Comment by bradleypeabody** [comment]
Yeah I'm around, just not many available cycles to work on this.  Overall I still think the concept has promise, but there's a lot of work required to make it into something that could be main stream or at least closer to it.

My general plan is essentially to wait for an opportunity for Vugu to be maintained and improved as part of some other project that has more resources.  And from there sort out what the big strides are that are needed.

I also think there are some larger features that would take a fair bit of work to sort out, but would really help adoption - for example better interoperability with JS, so one could add Vugu for specific sections of an existing UI project that uses something else.  Also the ability to mix and match components written as Vugu files vs being able to write them entirely in Go code - perhaps something almost similar to what jsx does.  I'm not a fan of the complexity these things would involve, but I do think there are very real motivations for having such features.  And unless/until there's resources to work on this, it's more or less a moot point for now.

But yeah, still here, I try to at least answer when I can, and hopefully something better can be worked out for the future.

**Comment by ZueffC** [comment]
thx for the answer!

**Comment by owenwaller** [comment]
In this case I am going to open an new issue to see what needs to happen to move Vugu towards a v1.0 release.

**Comment by owenwaller** [comment]
I have now opened the new issue to discuss what we might need to do to get Vugu to a v1.0 release. See #246

**Comment by owenwaller** [comment]
I think the conclusion now is that Vugu isn't abandoned :smile: 
See also issue #246
