### ISSUE TITLE
Request for a volunteer: TinyGo support for v1.0 (or shortly after)

### ISSUE THREAD

**Issue by owenwaller** [vugu/vugu#251]
At the minute the tentative plan is that we want to get Vugu to a v1.0 release using the standard Go compiler. This allows us to get the code base into slightly better shape (see the discussion under #246 for example).

Neither @bradleypeabody or myself are up to date with current state of TinyGo. So we have no idea what currently works and what doesn't.

There are some tests that should (or at least did) run under TinyGo, but against a older version. The latest TinyGo is v0.30.0 but the tests look like they are against v0.9.0. See [here](https://github.com/vugu/vugu/blob/885d6b14f1fe3b110fcf301e85e09025bd927009/tinygo-dev/Dockerfile#L4) for example.

As there is interest in the community in using TinyGo (and I think we should support it) could someone please try to run the Vugu tests against the current version of TinyGo? Then, tell us what breaks. Doing this would really help at this stage and we'd greatly appreciate it. Once we have an idea how much work there is we can try to prioritise it. In the meantime we can keep working towards the v1.0.

If anyone happens to already be using Vugu with the latest (or at least a more recent version) of TinyGo, can you please open a PR with any patches? Again, we'd hugely appreciate this.

Thanks

**Comment by Lord-Y** [comment]
I guess that can be closed then as I made this PR https://github.com/vugu/vugu/pull/257

**Comment by owenwaller** [comment]
I am going to close this because the v0.4.0 release makes two changes to how `vugu` uses the `tinygo` compiler suite.

1) Only the dockerized version of `tinygo` is used. We no longer use a local install of `tinygo`
2) The magefile always pulls the `tinygo` image based on the `latest` tag.

As a result there is no need to track the version of `tinygo`, it's not done automatically.

**Comment by owenwaller** [comment]
Closing
