### ISSUE TITLE
Prototype Statically Typed Components

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#28]
Right now, other than the root component, components are created and managed by the Environment (either JSEnv in browser or StaticHTMLEnv for server-side rendering).  The type of a component is not known until another component asks for it by it's tag name at which point it's looked up in the registry.

This has some subtle effects that I believe are undesirable and can be done better, such as the tags that component tag names and their properties (`vugu.Props`) are not type safe and only error at run time.

The idea I want to prototype is like this:

```html
<div class="root">
    <pkg:the-comp :SomeValue='&data.X' :SomeSetupMethod='data.Blah'>...</pkg:comp>
    <!-- pkg-the-comp might be better, not sure on syntax but functionality is the same -->
</div>

<script type="application/x-go">
import pkg "path/to/some/pkg"
</script>
```

The code generator then translates the tag name `pkg:the-comp` into the Go expression `pkg.TheComp`. And likewise `:SomeValue` (or `:some-value`, not sure on syntax yet) corresponds to a "SomeValue" variable.  And, since you can't have a member var and a method with the same name, we can detect that `SomeMethod` is a method and call it. (Actually this is probably not true - components in the same dir are code generated in an unspecified order, detecting names may not be possible, but a simple convention like "if this expression is surrounded with parens, it's a method call" might work; or maybe we just disallow methods entirely, and have a vg-new="" to specify a New... call, and everything else is just props - less functional but only slightly and much simpler).  The emitted Go could be something like:

```go
import pkg "path/to/some/pkg"

func (data *RootData)BuildVDOM(/*...*/) /*...*/ {
    // ...
    childComp := &pkg.TheComp{}
    childComp.SomeValue = &data.X
    childComp.SomeMethod(data.Blah)
    childComp.AfterPropsSet()
    // ...
}
```

It might be possible to eliminate the use of `vugu.Props` and the component type entirely and just use the "Data".  One struct per component - it certainly would be simpler.  But we do need to prove it doesn't stop us from doing useful things.  (This also ties into #14, because if we could put configuration data into the "environment" area, it reduces the need for "comp")

Stuff to remember:
* I am not sure if it's too much coupling to have parent components be doing `&pkg.TheComp{}` to instantiate `pkg:the-comp`.  Possibly the code generator could look for a `pkg.NewTheComp(/* args tbd */)` method and use it instead if it exists, and fallback to creating the struct itself.  This is probably better.
* The above code means components would need to manage child components during BuildVDOM, which they currently do not.  
* Means they probably need access to an "Environment" and be able to use it to keep track of which components are created, etc.  This code is currently in JSEnv.Render but would get splattered into each BuildVDOM. This doesn't sound great, but it's possible it could be made simple enough that it works.
* This also means BuildVDOM probably needs to move from the component type to the component instance data, and while we're at it, we should make it so the args and return are structs so we can easily add things without breaking new code.

One important question is with this type-safe approach, is it still possible to do "dynamic components", where the exact type used is determined at run time.  I think this would still be possibly by writing BuildVDOM manually, which would be needed in the current implementation anyway, so maybe this is fine.  But don't forget about - it's an important, if less-used, use case that will be needed for large apps.

**Comment by bradleypeabody** [comment]
I'm bumping this up in priority because it's a big change and if it's to be done it should be done early. Several other big issues (#7, #14, #5) are affected by it.

**Comment by bketelsen** [comment]
I did something like this last summer:
https://github.com/factorapp/playground/blob/master/pages/components.ghtml
May be worth digging to see the pros/cons of that approach, which is quite different from vugu, but does have namespaced components like you describe.

**Comment by bradleypeabody** [comment]
Just another note on this is to not forget how to deal with some properties being hard fields but have the option of components just getting all other properties passed in as a generic map or something. I.e. if you pass a property to a component that it knows about it should be set in a type safe way which fails at compilation if not.  But you also need the ability to just "pass through" things that you want to end up on an HTML tag but don't otherwise need to look at.  In order to make the calling component not have to understand too much about the compnent it's calling it might require a different syntax, e.g. `:prop` means a hard field, whereas `-prop` would just get added to a generic map - something like that could work.

**Comment by bradleypeabody** [comment]
Note to self on syntax:

```
<!-- this could mean look for a Go struct field named "Prop", and fail on bad name or bad type -->
<pkg:comp :Prop="x"/> 

<!-- while this could mean to pass "prop" in a member of map, for dynamic attributes that the component will parse manually -->
<pkg:comp :prop="x"/>
```

**Comment by bradleypeabody** [comment]
This is now done and merged into master.
