### ISSUE TITLE
wasm fails to load in Safari, but should work

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#3]
Problem is lack of support for WebAssembly.instantiateStreaming.  Need to go through and find instances of that and add fallback that just uses WebAssembly.instantiate.  Test on Safari desktop and Safari mobile.

**Comment by erinpentecost** [comment]
The failback is the following snippet, right? This should define InstantiateStreaming when not present, so you don't need to stick the branch on top of every instance of the code.
```js
if (!WebAssembly.instantiateStreaming) {
    WebAssembly.instantiateStreaming = async (resp, importObject) => {
    const source = await (await resp).arrayBuffer();
    return await WebAssembly.instantiate(source, importObject);
    };
}
```

**Comment by bradleypeabody** [comment]
Nice; yeah it looks right to me.  (And it seems that async/await is better supported than wasm so no worries there.)  I'll drop that into the default page template it outputs, give it a little testing, and merge it in.

**Comment by ptxmac** [comment]
I also hit this and I've created a patch for it: #27
