### ISSUE TITLE
Starter guide results in errors

### ISSUE THREAD

**Issue by bevand10** [vugu/vugu#33]
**Describe the bug**
Code from the Getting Started / marvel at your work example fails.

**Software Versions**
Vugu version: latest v0.0.0-20190404005108-af4e6cfeb9d6
Go version: 1.12 Ubuntu 
Browser and version: Chromium Version 73.0.3683.75 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**To Reproduce**
Followed the getting started instructions.

```
$ dpkg --list|grep golang
ii  golang-1.11-race-detector-runtime           0.0+svn332029-0ubuntu1~longsleep1+xenial      amd64        Runtime support for Go's race detector
ii  golang-1.12-go                              1.12-1longsleep2+xenial                       amd64        Go programming language compiler, linker, compiled stdlib
ii  golang-1.12-src                             1.12-1longsleep2+xenial                       amd64        Go programming language - source files
ii  golang-go                                   2:1.12~1longsleep1+xenial                     amd64        Go programming language compiler, linker, compiled stdlib
ii  golang-race-detector-runtime                2:1.11~0ubuntu1~longsleep1+xenial             amd64        Runtime support for Go's race detector
ii  golang-src                                  2:1.12~1longsleep1+xenial                     amd64        Go programming language - source files
$
$ go version
go version go1.12 linux/amd64
$
$ cat go.mod 
module github.com/bevand10/tips

go 1.12

require github.com/vugu/vugu v0.0.0-20190404005108-af4e6cfeb9d6 // indirect
$
$ cat root.vugu 
<div class="my-first-vugu-comp">
    <button @click="data.Toggle()">Test</button>
    <div vg-if="data.Show">I am here!</div>
</div>

<style>
.my-first-vugu-comp { background: #eee; }
</style>

<script type="application/x-go">
type RootData struct { Show bool }
func (data *RootData) Toggle() { data.Show = !data.Show }
</script>
$
$ cat devserver.go 
// +build ignore

package main

import (
	"log"
	"net/http"
	"os"

	"github.com/vugu/vugu/simplehttp"
)

func main() {
	wd, _ := os.Getwd()
	l := "127.0.0.1:8844"
	log.Printf("Starting HTTP Server at %q", l)
	h := simplehttp.New(wd, true)
	// include a CSS file
	// simplehttp.DefaultStaticData["CSSFiles"] = []string{ "/my/file.css" }
	log.Fatal(http.ListenAndServe(l, h))
}
$
$ cat Makefile 
.PHONY:	run

run:
	go run devserver.go
$
$ make
go run devserver.go
2019/04/05 10:55:49 Starting HTTP Server at "127.0.0.1:8844"
2019/04/05 10:55:55 http: superfluous response.WriteHeader call from github.com/vugu/vugu/simplehttp.(*SimpleHandler).serveGoEnvWasmExecJs (simple-handler.go:325)
```

And from the Chrome console:
```
(index):11 GET http://127.0.0.1:8844/wasm_exec.js net::ERR_ABORTED 500 (Internal Server Error)
(index):28 Uncaught ReferenceError: Go is not defined
    at (index):28
Navigated to http://127.0.0.1:8844/
```

**Expected behavior**
Something other than errors, and just a spinner in the middle of the page.

**Comment by bevand10** [comment]
Closing this.

Turns out there's a bug in the current Ubuntu debian package distribution of go, preventing your code from finding the misc/wasm folder,

Fix was as follows:
```
$ sudo -i
# cd /usr/lib/go-1.12
# ln -s ../../share/go-1.12/misc .
```

**Comment by bradleypeabody** [comment]
Okay, makes sense.  Glad it worked out.

**Comment by kneal** [comment]
Did anyone run into the issue where when the main_wasm.go file gets generated you get a collision on the main function?

```
2019/04/15 10:47:45 Error from compile: exit status 2 (out path="/var/folders/tv/fk0mbn7j53l9xh5n6ydwk3ndbdt82j/T/main_wasm_129578788"); Output:
./main_wasm.go:13:6: main redeclared in this block
        previous declaration at ./devserver.go:11:6
```

**Comment by bradleypeabody** [comment]
@kneal Take a look at the [build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints) at the top of each of the relevant files.  devserver.go is intended to have `// +build ignore` at the top, so it's main func won't conflict with the one in main_wasm.go

**Comment by MwumLi** [comment]
why close the issue? The starter cann't run in mac. The erros is below:  
```
/main_wasm.go:13:6: main redeclared in this block
        previous declaration at ./devserver.go:11:6
```
![image](https://user-images.githubusercontent.com/6889433/61447408-74fc1c00-a983-11e9-9889-f8b6ee96e609.png)  

Viste <http://127.0.0.1:8844> After `go run devserver.go`, the file structure is below:  
![image](https://user-images.githubusercontent.com/6889433/61447465-95c47180-a983-11e9-8f58-4b7c1e2844a5.png)

**Comment by bradleypeabody** [comment]
@MwumLi You are most likely missing the `// +build ignore` from the top your devserver.go file (see https://www.vugu.org/doc/start ).  Or, you might have some other issue which is causing it to not be recognized - see https://golang.org/pkg/go/build/#hdr-Build_Constraints

If you are still having problems please post your devserver.go so I can take a look.

**Comment by MwumLi** [comment]
😸This works to me
