### ISSUE TITLE
Is there a Discord Chat?

### ISSUE THREAD

**Issue by AGoblinKing** [vugu/vugu#42]
**Question**
Is there a Discord Chat?

**Is your question related to a problem? Please describe.**
Other similar open source projects create discord chats to create a community.

**Suggested Changes**
Create a Discord Chat if you haven't already.

**Additional context**
http://discord.gg && https://svelte.dev/ <- notice the chat button that leads to discord on the svelte website.

**Comment by AGoblinKing** [comment]
I'm pretty excited about your project and would love to keep tabs on it. I'm in the process of switching my client over to go-lang and vugu seems like an easy replacement for svelte. A discord chat would help me keep up to date on what's going with vugu.

**Comment by bradleypeabody** [comment]
No Discord, but how about using Slack?

https://invite.slack.golangbridge.org/

Channel #vugu

**Comment by AGoblinKing** [comment]
Thanks, update the README w/ a slack shield for it?

**Comment by bradleypeabody** [comment]
Good idea, added that under the Updates section: https://github.com/vugu/vugu/blob/master/README.md

**Comment by bradleypeabody** [comment]
I think we're good on this.  I'll go ahead and close it now.

**Comment by carepollo** [comment]
a discord server would help a lot

**Comment by owenwaller** [comment]
@carepollo 

This issue has been closed for more then 4 years now. If you believe this is a critical new issue then please open a new issue. By responding to closed issues you are creating noise for @bradleypeabody  and myself.

As @bradleypeabody has already said there is a #vugu channel on slack. 

If you need it, there is a Slack invite link in the Go Docs:

https://pkg.go.dev/github.com/vugu/vugu#section-readme

Hopefully that will be will help you.

Aside: but we do now appear to be missing the Readme.md from the root of the `vugu` repo. @carepollo had you not commented on this issue I would not have found this, so thank you for that. I will now open a new issue to track this.
