### ISSUE TITLE
Root HTML

### ISSUE THREAD

**Issue by 1995parham** [vugu/vugu#43]
**Question**
I have a root component that is named root.vugu but I want to have a root HTML file to include general style files and configure some things like HTML header and more. Is there any way for this?

**Comment by bradleypeabody** [comment]
The functionality that is available right now is that in the `simplehttp` package it provides a basic HTML page that you can customize.  The source for it is a package variable here: https://godoc.org/github.com/vugu/vugu/simplehttp#pkg-variables  Using a combination of `DefaultPageTemplateSource` and/or `DefaultTemplateDataFunc` you should be able to accomplish what you're describing.

Overall, there is a refactor in progress (including this issue: https://github.com/vugu/vugu/issues/5) which will allow you to put an <html> tag directly in root.vugu and include the items you describe right in there.  I hope to have that feature ready soon and will certainly announce it when it's available.

**Comment by 1995parham** [comment]
@bradleypeabody Thanks for your complete response. I will check it. I want to thank you for this awesome project. I am trying to create an example project with Vugu in order to show its features.
