### ISSUE TITLE
Using multiple components doesn't seem to work

### ISSUE THREAD

**Issue by dolanor** [vugu/vugu#44]
**Describe the bug**
I have a component `<my-line>` enclosed in `<ul>`. It is a simple `<li>`. If I write:
```
<ul>
<my-line file-name="foo">
<my-line file-name="bar">
</ul>
```
it only displays `foo` but not `bar`.

I'm aware of the `<my-line vg-for='xxx'>`, but I don't find it as flexible as if we could just write more `<my-line>` elements. And also I find that a vg-for inside a component that is supposed to instantiate more component of the same type a little bit counter intuitive.
Is it possible? Is it normal/work as designed?

**Software Versions**
Vugu version: ` 0a722f1`
Go version: `1.12.4`
Browser and version: `firefox 66.0.3 (linux)`

**To Reproduce**
See the description

**Expected behavior**
Display a list of my-line components

**Comment by dolanor** [comment]
Forget about it, I don't know about vue at all and am discovering through this. So it seems the correct way to do for in vue. Therefore, it is good. I just need to wrap my head around it.
Thanks for the awesome lib otherwise :)

**Comment by bradleypeabody** [comment]
This is probably a legitimate bug, but the relevant code is being reworked as I write this.  Look out for a push to master soon with a significant refactor in the component code and please re-test after that.

**Comment by tbruyelle** [comment]
Got the same issue and fixed it by closing the component tags :

```html
<ul>
<my-line file-name="foo"></inline>
<my-line file-name="bar"></inline>
</ul>
```

**Comment by bradleypeabody** [comment]
Thank you and sorry yeah this was just a silly typo in not closing the tags in the doc.  It's fixed now.

**Comment by tbruyelle** [comment]
No problem @bradleypeabody thanks for this amazing project, I started a small personal project with it and I'm very happy (I used vecty in the past and found vugu offers also a very interesting way to build webapps).
Keep going it's great !  :)
