### ISSUE TITLE
I can't seem to find one pic/screenshot anywhere

### ISSUE THREAD

**Issue by MostHated** [vugu/vugu#54]
I looked here, as well as all through the vugu site and I can't find a single pic, screenshot, app demo, etc? I would imagine for a UI framework you might want to at least have some pics / demos of things that one might be able to expect a typical UI to look like.

Thanks,
-MH

**Comment by vinhjaxt** [comment]
Here you are:
![image](https://user-images.githubusercontent.com/8877695/61576327-09d95380-ab03-11e9-81ca-0de3027218d0.png)
![image](https://user-images.githubusercontent.com/8877695/61576340-4016d300-ab03-11e9-9d00-e32a8e3aaf1b.png)
![image](https://user-images.githubusercontent.com/8877695/61576343-486f0e00-ab03-11e9-8cc3-671e84a670b5.png)

**Comment by bradleypeabody** [comment]
@MostHated Yup, you're right, that stuff should exist.  It does not yet.  At the moment, Vugu is little more than a code converted.  But once a few more things are sorted out, a framework will become available and documented, etc.  Contributions are welcome, e.g. https://github.com/vugu/vugu/issues/53

**Comment by MostHated** [comment]
No worries, I mostly brought it up because it looks like quite an interesting project and it definitely helps bring folks in the door, especially when it comes to something based on UI. I can definitely understand that that kind of stuff isn't as important as working on the actual project and it's no huge rush. I just wanted to make sure I didn't miss a section of the site or something, lol.

Keep up the good work!
Thanks,
-MH

**Comment by bradleypeabody** [comment]
Awesome and thanks 👍
