### ISSUE TITLE
I try to follow the documentation, but failed

### ISSUE THREAD

**Issue by kingAnyWHere** [vugu/vugu#55]
I try to follow the documentation https://www.vugu.org/doc/start, but it seems that https://golang.org/x/text?go-get=1 does not exist. Here is my error log, hoping to get feedback. Thank you
my go version is 1.12.7
My network is normal

PS C:\Users\sky\Desktop\testapp> go run devserver.go
go: finding github.com/vugu/vugu/simplehttp latest
go: finding github.com/vugu/vugu latest
go: golang.org/x/text@v0.3.0: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go: golang.org/x/net@v0.0.0-20190328230028-74de082e2cca: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go: golang.org/x/tools@v0.0.0-20190407030857-0fdf0c73855b: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go: error loading module requirements

PS C:\Users\sky\Desktop\testapp> go version
go version go1.12.7 windows/amd64
PS C:\Users\sky\Desktop\testapp>

**Comment by bradleypeabody** [comment]
Looks very much like a local network/firewall issue to me. Taking a cue from the message `dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)`  - when I try that IP:port from my network:

```
nc -v 216.239.37.1 443
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 10.138.104.132 port 56344
	dst 216.239.37.1 port 443
	rank info not available
	TCP aux info available

Connection to 216.239.37.1 port 443 [tcp/https] succeeded!
```
