### ISSUE TITLE
how to Integrate devserver into echo？

### ISSUE THREAD

**Issue by ystyle** [vugu/vugu#61]
**Question**
I want to integrate devserver into echo or devserver can proxy some api path to echo server `(like webpack's proxytable)`

**Comment by bradleypeabody** [comment]
Please provide more information.  The server setup in devserver.go is pretty straightforward and should work with whatever proxying would be done with any other Go application.  If you let me know more specifically what you are trying, etc. and I can help point you in the right direction.

**Comment by ystyle** [comment]
init vugu's devserver: `h := simplehttp.New(wd, true)`
init echo server: `e := echo.New()`

how can i route `/api/*` to echo , route `/` to vugu devserver ?

other issue: 
and my project struct:
myproject
- cmd
  - server
    - resfull.go
  - uidev
    - devserver.go
- config
- internal
  - ui
    - root.vugu

init vugu devserver width `h := simplehttp.New(wd + "/internal/ui", true)`
it will Compile Error,  and don't generate `main_wasm.go` .
move devserer.go to `/internal/ui`, will generate another go.mod, file in `/internal/ui`

**Comment by bradleypeabody** [comment]
> how can i route /api/* to echo

This is an echo question and I'm not familiar with it.

But `h` in this case is just an http.Handler, and you can call it in whatever case you please.  I imagine you can register some sort of handler with echo and then do something like `if strings.HasPrefix("/some-prefix/") { h.ServeHTTP(w, r) } ` (assuming you can get to the w and r in an echo handler).

> it will Compile Error

I can help tell you what it means if you provide the specific error.

**Comment by ystyle** [comment]
1. Proxy to the echo server, I used the following method, but I would like to be like webpack devserver tool
```go
        e := echo.New()
	ui := e.Group("/ui")
	target, _ := url.Parse("http://127.0.0.1:8844")
	ui.Use(middleware.ProxyWithConfig(middleware.ProxyConfig{
		Balancer:  middleware.NewRandomBalancer([]*middleware.ProxyTarget{
			{
				Name: "ui",
				URL:  target,
			},
		}),
		Rewrite: map[string]string{
			"/ui/*": "/$1",
		},
	}))
```

>Can simplehttp have a built-in proxy plugin? 

2. After I use `h.ParserGoPkgOpts.SkipGoMod = true` , Can be compiled through， and `go.mod` skip generate

**Comment by bradleypeabody** [comment]
I don't see why you need a proxy.  HTTP Proxy definition:

https://stackoverflow.com/questions/7155529/how-does-http-proxy-work
https://en.wikipedia.org/wiki/Proxy_server
https://www.techopedia.com/definition/12835/http-proxy

An HTTP proxy creates new outbound connections for each incoming request.

Everything is in Go, you can just call what you need a function/method call.

`simplehttp.New` returns a value that is compatible with [http.Handler](https://golang.org/pkg/net/http/#Handler).  Which means you can call the ServeHTTP method on it to handle requests.  Please take a moment to study up on http.Handler if you are unfamiliar with it.  You can just call it directly.

**Comment by bradleypeabody** [comment]
I haven't tried this but looking at their docs it seems like something like this would work:

```go
sh := simplehttp.New(wd, true)
e := echo.New()
e.GET("/vuguapp", echo.WrapHandler(http.StripPrefix("/vuguapp", sh))
```

And then you need to change the default HTML that is output to add the "/vuguapp" prefix in everywhere a path is referenced. (With something like `simplehttp. DefaultPageTemplateSource  = "..."` and get and edit the template source from here: https://github.com/vugu/vugu/blob/master/simplehttp/simple-handler.go#L381)

**Comment by bradleypeabody** [comment]
I'm assuming this was resolved. Closing this.
