### ISSUE TITLE
Develop official website via vugu as a real example.

### ISSUE THREAD

**Issue by lunny** [vugu/vugu#66]
I noticed https://www.vugu.org is not written by vugu. If it is that, that's great and could be an example.

**Comment by bradleypeabody** [comment]
Vugu.org is indeed written using Vugu. Source code is here: https://github.com/vugu/vugu-site

More examples are coming as soon as the component-refactor branch can be merged into master - since that will change and break some things.  Hopefully in the next few weeks.
