### ISSUE TITLE
Run pure binary file on a no-golang server

### ISSUE THREAD

**Issue by xuezhaojun** [vugu/vugu#67]
**Question**
Hi，I tried to run my vugu project on a server， but then I found I have to run vugu project on a server with golang env，because vugu builds wasm-exec.js in running.

Can I just build a binary file, throw it on a server(without go) and run? I really hope vugu can do this.

Thanks for your hard work!

**Comment by bradleypeabody** [comment]
Yes, this is definitely possible.  Please have a look at https://www.vugu.org/doc/build-and-dist in the "Building dist.go" section for instructions on how to build production output.  This will produce static files that can be served with most any regular webserver, e.g. nginx, apache, static CDN like AWS S3+CloudFront, etc.

**Comment by xuezhaojun** [comment]
> Yes, this is definitely possible. Please have a look at https://www.vugu.org/doc/build-and-dist in the "Making dist.go" section for instructions on how to build production output. This will produce static files that can be served with most any regular webserver, e.g. nginx, apache, static CDN like AWS S3+CloudFront, etc.

Thanks for your reply, I tried use `dist.go` and it worked! 
I have this question partly is because I'm new to frontend tech, and at first, I thought the binary file will contain static files like "main.wasm", "wasm_exec.js"
I'm in a startup company, I'm a backend developer, and our tech team is small.
So I use vugu to build internal systems for other teams to use, vugu is very handy and efficient, it helps me a lot!
Thank you again for this beautiful work.
