### ISSUE TITLE
fix tests, get travis working again

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#75]
Various tests are failing. Travis config needs update to Go 1.13 and then we need to either remove inapplicable tests or fix them.

**Comment by forstmeier** [comment]
@bradleypeabody is this issue still active? I might have some time to take a look at it, or another pressing/small issue you have in mind, to get into helping with this project. It's awesome, by the way!

**Comment by bradleypeabody** [comment]
Thanks @forstmeier!  On this issue, I actually I think it's all good now.  I did a hit on tests not too long ago and made a test suite that runs wasm stuff in a headless browser, that's been working well enough.

I'm going to close this issue. But if you see something else that is in your wheelhouse, definitely hit me up.
