### ISSUE TITLE
.css files use

### ISSUE THREAD

**Issue by bh90210** [vugu/vugu#77]
**Question**
I might be missing something obvious here but how could I somehow use external `.css` files?

**Comment by itstmyi** [comment]
It seems there is something(https://github.com/vugu/vugu/tree/master/full-test-data/test3) about css but I am not familiar to it .Good luck.

**Comment by bh90210** [comment]
again, my mistake
in the getting started https://www.vugu.org/doc/start it has a commented out example of loading an external `.css`

```go
        // include a CSS file
	// simplehttp.DefaultStaticData["CSSFiles"] = []string{ "/my/file.css" }
```

**Comment by bradleypeabody** [comment]
@bh90210 With v0.1.0 (which is what go build will pull by default) the above is the best way.  There is new code on master which will hopefully be tagged soon which allows you to include CSS `<link>` tags in your .vugu files directly.
