### ISSUE TITLE
How can I create a (datalist) html element dynamicly for (input type="text") html element ?

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#79]
I need a selection component (combined box)  . 
I  study it and think maybe the  example "full-test-data/test3" can be used .
Is there any better method available ? 

BTW :
 I can't pass parameters to "option" component until now by (.value) or (:value)  to make a datalist html element . Could a  new sample be provided ?

Thanks .

**Comment by bradleypeabody** [comment]
I'm sorry I don't fully understand.  Perhaps you can provide an example (link or snippet) to something showing the intended output?  Or do you have some pseudo code that doesn't work now but demonstrates what you would like it to do?

**Comment by itstmyi** [comment]
The following is my code for a HTML5 select element(selection box)  according to the sample(wasm-test-suite/test-004-component).
No error is shown but there is no items in the selection box after I click the button in Chrome browser(78.00，windows 7 professional ,x64 , go 1.13) .

Thanks for any information .

go.mod 
---------
module selectionbox

require (
	github.com/vugu/vjson v0.0.0-20191111004939-722507e863cb
	github.com/vugu/vugu v0.1.1-0.20191130191251-de1d40627b52
)

go 1.13
----------
root.vugu
-----------
<html>
    <head>
        <title>Test page</title>
    </head>
    <body>
        <div class="test-div" id="testdiv">
            <select id="dl0">
                <main:DemoLine vg-for="i := 0; i < c.ItemCount; i++" vg-key="i" :Num="i"></main:DemoLine>
            </select>
            <button id="addbtn" @click="c.OnShowSelect()">Add</button>
        </div>
    </body>
</html>

<style>
#test_div_id {
    background: #ddd;
}
</style>

<script type="application/x-go">

type Root struct {
    ItemCount int `vugu:"data"`
}

func (c *Root) BeforeBuild() {
    if c.ItemCount == 0 {
        c.ItemCount = 3
    }
}

func (c *Root) OnShowSelect() {
    c.ItemCount++
}

</script>
-----------------
demo-line.vugu
------------------
<option class="demo-line" .value="c.Num" vg-html="c.Num"></option>

<style>
.demo-line {
    color: red;
}
</style>
        
<script type="application/x-go">

type DemoLine struct {
    Num int `vugu:"data"`
}

</script>

**Comment by bradleypeabody** [comment]
Do you need to have the `<option>` tag inside a separate component?  Does it work if you just do something like this:

```go
<select>
    <option vg-for="i := 0; i < 3; i++" vg-key="i" :value="i" vg-html="i"></option>
</select>
```

**Comment by itstmyi** [comment]
It works . Thanks .
