### ISSUE TITLE
Rendering became slow after v0.1.0

### ISSUE THREAD

**Issue by tbruyelle** [vugu/vugu#87]
**Describe the bug**
The latest refactor seems to slow down a lot the rendering phase, compared to v0.1.0. I have a working webapp coded in v0.1.0, which uses to render instantly. I ported it to vugu master, and now it is very slow, the console is filled with a lot of stuff like `processing opcode`. I didn't measured but it's at least x10 in term of rendering duration.
(By rendering I mean the first time the app is displayed, and each time it's re-rendered)

**Software Versions**
Vugu version: fa72e903246bf90a0b548f7bb4dd607b9d60f4d4
Go version: 1.13.4
Browser and version: Version 78.0.3904.108 (Official Build) Arch Linux (64-bit)

**To Reproduce**
Compare a vugu app build by v0.1.0 and an other one build by master.

**Expected behavior**
The rendering should be fast

**Comment by tbruyelle** [comment]
OK, I removed some `console.log`  and things get a lot better. Feel free to close the issue.

**Comment by bradleypeabody** [comment]
Ok cool - yeah the logging should come out and it's almost certainly the cause of the slow.  I will leave this open to track that change.

**Comment by bradleypeabody** [comment]
I believe this commit addresses this issue: https://github.com/vugu/vugu/commit/bc867b629dcac11ace32b56baffbe37c3bdfecb2

Feel free to make another issue if more random debug logging shows up again.

**Comment by tbruyelle** [comment]
That should do the trick, thx
