### ISSUE TITLE
vg-for and events: value and key are not captured

### ISSUE THREAD

**Issue by tbruyelle** [vugu/vugu#89]
**Describe the bug**
Inside a loop, when using `value` or `key` variable inside a event attribute (like `@click`), the last value of `key/value` of the loop is always used, because they are not captured.

**Software Versions**
Vugu version: d1cd4bcee583c7d794f2d1278962e98662b39a6e
Go version: 1.13.5
Browser and version: Brave Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) unknown (64-bit)

**To Reproduce**
A PR will follow with a failing test case.

**Expected behavior**
`key/value` inside event attribute should keep their value at the moment they are used.

**Additional Notes**
There's a TODO for that, but I have no idea on how to achieve that properly :
https://github.com/vugu/vugu/blob/master/gen/parser-go.go#L794

**Comment by bradleypeabody** [comment]
Interesting - good point.

This one needs some careful thought.

Generally it seems fine to have two sets of variables, one from the for statement and one that is inside the loop's scope.  But there is the question of how to name these so they are sane and consistent and also how to make it clear to the user which is which.

Logically if I put variable names in vg-for I am going to, as a user of the library, want to reference those variable names later.  Having some other alternate name that I can't see which means the version that is captured inside the loop - I feel like that's going to be confusing.

Ideally whatever syntax and names are used would:

- Translate in an obvious way to a Go `for`
- Allow the user to choose variable names used in the `for` statement but provide sensible defaults as a shorthand
- We need vgiterkey to be defined sensible in order for caching to work

Possibly another attribute could be introduced which gives variable declarations inside the loop, e.g. `<div vg-for="k, v := range w" vg-var="k2 := k; v2: = v">` (the vg-var stuff is emitted inside the loop).

I will think about this more. I'm definitely open to suggestions.

**Comment by tbruyelle** [comment]
Indeed I manage to provide a fix for when the user doesn't provide the variable name (so by default he knows this implies to use `key` and `value`), but this doesn't work for the other case, when he provides the variable name.

Maybe we could *cheat* on the variable names, for instance if the user declares

```html
<div vg-for='k, v := range w'>
```

the generated code is

```go
for k_, v_ := range w {
  k, v := k_, v_ 
 ....
}
```

What do you think ?

**Comment by bradleypeabody** [comment]
I'm still thinking about this, but have a look at this example: https://play.golang.org/p/FSbh6-qOZtI

The `k` and `v` can be shadowed inside the loop with values for the current iteration (only `v` shown in the example but it's the same idea for `k`).

It's similar to your idea but doesn't require any name mangling.

I agree that having to use additional attributes as the common case with each vg-for should be avoided if possible.

I would be okay with automatically shadowing the variables as long as disabling this feature would be feasible as well if it becomes needed.  I can't think of a case right now to not shadow the variables in a loop, but I don't think it's wise to assume that this case won't arise.

**Comment by tbruyelle** [comment]
Wow I never though something like `v := v` would compile ! That's cool I will base the change on that, thanks.

I have an other question, about `vgiterkey` this time. If I understood well it's used to build the component key, in order to distinguish the same component but in different iteration of a loop. So basically it's equal to the loop index. For one specific case I suspect there's a bug, because it ends with a compilation error in the generated file.

Consider this vugu code :
```html
<p vg-for='k, v := c.Items' vg-html='v'></p>
```

It results a vgiterkey defined like that:
```go
var vgiterkey interface{} = , 
```

The culprit code in `gen/parsing-go.go` : 
```go
       // if still no vgiterkeyx use the first identifier
	if vgiterkeyx == "" {
		vgiterkeyx = strings.FieldsFunc(forx, func(r rune) bool {
			return unicode.IsLetter(r) || unicode.IsDigit(r)
		})[0]
	}
```

I don't understand why this code tries to split `forx` on letters or digits. If you want to find the first identifier, it should split `forx` on `,` or `:`. WDYT ?

**Comment by bradleypeabody** [comment]
I pushed a small change on this and a test case recently (https://github.com/vugu/vugu/commit/1d61909d49133b5a54e92ae453b18fdc1a744f3b), I was trying to extract the first variable name from the for expression.

This probably should be changed to a regexp match for exact cases and it can error if it finds something it doesn't understand.  The only useful cases I can see would be:

- `k, v := `...
- `_, v := `... (use v as vgiterkey in this case)
- `k := `...

Obviously the variable names can be anything valid and whitespace variations should be allowed.

If the caller puts anything else in there we just error.  And if some other valid case comes up it just gets added to the list of valid cases.

**Comment by bradleypeabody** [comment]
How about supporting `vg-for.noshadow=` to disable the variable shadowing behavior?  I think it would be trivial to implement, it makes the default behavior of `vg-for=` be the most useful one (with shadowing), but provides a convenient and fairly obvious way to disable it.  Vue uses this syntax of `.option` appended to various attributes to invoke alternate behaviors and while I'm not in love with it, it works and I don't see a better way.

**Comment by tbruyelle** [comment]
Ok for that way to express options, I will go for that.

**Comment by bradleypeabody** [comment]
I believe this was fully resolved with the variable shadowing support that was added.  Thanks for your help on this @tbruyelle!
