### ISSUE TITLE
How to delete/update/load a child component dynamicly from a root/parent component ?

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#92]
For example , a new child component is needed for appending in root.vugu(parent component) . I see that "vg-if" can be used for visible or not , but that would occupy running resource  . Another case is to replace one child component with the other in parent component  to show a new page. 

Thanks .

**Comment by bradleypeabody** [comment]
Can you give me example of what you like to be able to write?  That might help me understand your question.

**Comment by itstmyi** [comment]
append a new vugu component file(demo-line-new.vugu) to wasm-test-suite/test-004-component (find the attached txt file please).
The new component is named as "DemoLineNew" , and I only change the <style> code from "blue" to "red" to simplify my question .
I wonder how I can replace the "DemoLine" component with the new "DemoLineNew" component dynamicly in root.vugu .
[demo-line-new.vugu.txt](https://github.com/vugu/vugu/files/3971157/demo-line-new.vugu.txt)

**Comment by bradleypeabody** [comment]
It seems to me like a simple `vg-if` would work for this.  The calling code could do something like:

```html
<main:DemoLine vg-if="someflag" />
<main:DemoLineNew vg-if="!someflag" />
```

Is there a reason that wouldn't work?

> I see that "vg-if" can be used for visible or not , but that would occupy running resource

`vg-if` emits a literal `if` statement in the generated code and the appropriate component is only created/reused if the condition is met.  Branches in the code that are not taken do not result in allocations or occupy heap memory.

**Comment by itstmyi** [comment]
My expected answer . Thanks .
